export const ENCHANTMENTS = [
  // ── Armor Enchantments (attribute +1~+3) ──
  { name: 'STR +1', slug: 'armor-str-1', system: 'armor' as const, effects: { str: 1 }, available_latam: true },
  { name: 'STR +2', slug: 'armor-str-2', system: 'armor' as const, effects: { str: 2 }, available_latam: true },
  { name: 'STR +3', slug: 'armor-str-3', system: 'armor' as const, effects: { str: 3 }, available_latam: true },
  { name: 'AGI +1', slug: 'armor-agi-1', system: 'armor' as const, effects: { agi: 1 }, available_latam: true },
  { name: 'AGI +2', slug: 'armor-agi-2', system: 'armor' as const, effects: { agi: 2 }, available_latam: true },
  { name: 'AGI +3', slug: 'armor-agi-3', system: 'armor' as const, effects: { agi: 3 }, available_latam: true },
  { name: 'VIT +1', slug: 'armor-vit-1', system: 'armor' as const, effects: { vit: 1 }, available_latam: true },
  { name: 'VIT +2', slug: 'armor-vit-2', system: 'armor' as const, effects: { vit: 2 }, available_latam: true },
  { name: 'VIT +3', slug: 'armor-vit-3', system: 'armor' as const, effects: { vit: 3 }, available_latam: true },
  { name: 'INT +1', slug: 'armor-int-1', system: 'armor' as const, effects: { int: 1 }, available_latam: true },
  { name: 'INT +2', slug: 'armor-int-2', system: 'armor' as const, effects: { int: 2 }, available_latam: true },
  { name: 'INT +3', slug: 'armor-int-3', system: 'armor' as const, effects: { int: 3 }, available_latam: true },
  { name: 'DEX +1', slug: 'armor-dex-1', system: 'armor' as const, effects: { dex: 1 }, available_latam: true },
  { name: 'DEX +2', slug: 'armor-dex-2', system: 'armor' as const, effects: { dex: 2 }, available_latam: true },
  { name: 'DEX +3', slug: 'armor-dex-3', system: 'armor' as const, effects: { dex: 3 }, available_latam: true },
  { name: 'LUK +1', slug: 'armor-luk-1', system: 'armor' as const, effects: { luk: 1 }, available_latam: true },
  { name: 'LUK +2', slug: 'armor-luk-2', system: 'armor' as const, effects: { luk: 2 }, available_latam: true },
  { name: 'LUK +3', slug: 'armor-luk-3', system: 'armor' as const, effects: { luk: 3 }, available_latam: true },

  // ── Fallen Angel Wings Enchantments ──
  { name: 'Fighter Spirit', slug: 'faw-fighter-spirit', system: 'fallen_angel' as const, effects: { atk: 3 }, available_latam: true },
  { name: 'Super Strength', slug: 'faw-super-strength', system: 'fallen_angel' as const, effects: { str: 5 }, available_latam: true },
  { name: 'Super Agility', slug: 'faw-super-agility', system: 'fallen_angel' as const, effects: { agi: 5 }, available_latam: true },
  { name: 'Super Vitality', slug: 'faw-super-vitality', system: 'fallen_angel' as const, effects: { vit: 5 }, available_latam: true },
  { name: 'Super Intelligence', slug: 'faw-super-intelligence', system: 'fallen_angel' as const, effects: { int: 5 }, available_latam: true },
  { name: 'Super Dexterity', slug: 'faw-super-dexterity', system: 'fallen_angel' as const, effects: { dex: 5 }, available_latam: true },
  { name: 'Super Luck', slug: 'faw-super-luck', system: 'fallen_angel' as const, effects: { luk: 5 }, available_latam: true },
  { name: 'Critical Stone', slug: 'faw-critical-stone', system: 'fallen_angel' as const, effects: { crit: 3 }, available_latam: true },
  { name: 'Fatal', slug: 'faw-fatal', system: 'fallen_angel' as const, effects: { crit: 5, atk: 1 }, available_latam: true },
  { name: 'Healing Factor', slug: 'faw-healing-factor', system: 'fallen_angel' as const, effects: { healing_power: 3 }, available_latam: true },
  { name: 'Attack Speed', slug: 'faw-attack-speed', system: 'fallen_angel' as const, effects: { aspd: 1 }, available_latam: true },
  { name: 'Piercing Shot', slug: 'faw-piercing-shot', system: 'fallen_angel' as const, effects: { long_range_damage: 2 }, available_latam: true },
  { name: 'Evasion', slug: 'faw-evasion', system: 'fallen_angel' as const, effects: { flee: 5 }, available_latam: true },
  { name: 'Sharp Eye', slug: 'faw-sharp-eye', system: 'fallen_angel' as const, effects: { hit: 5 }, available_latam: true },

  // ── Archangel Wings Enchantments ──
  { name: 'Holy Resistance', slug: 'aw-holy-resistance', system: 'archangel' as const, effects: { res_holy: 5 }, available_latam: false },
  { name: 'Dark Resistance', slug: 'aw-dark-resistance', system: 'archangel' as const, effects: { res_dark: 5 }, available_latam: false },
  { name: 'Fire Resistance', slug: 'aw-fire-resistance', system: 'archangel' as const, effects: { res_fire: 5 }, available_latam: false },
  { name: 'Water Resistance', slug: 'aw-water-resistance', system: 'archangel' as const, effects: { res_water: 5 }, available_latam: false },
  { name: 'Wind Resistance', slug: 'aw-wind-resistance', system: 'archangel' as const, effects: { res_wind: 5 }, available_latam: false },
  { name: 'Earth Resistance', slug: 'aw-earth-resistance', system: 'archangel' as const, effects: { res_earth: 5 }, available_latam: false },
  { name: 'Boss Damage', slug: 'aw-boss-damage', system: 'archangel' as const, effects: { damage_vs_boss: 3 }, available_latam: false },
  { name: 'HP Recovery', slug: 'aw-hp-recovery', system: 'archangel' as const, effects: { hp_regen: 5 }, available_latam: false },
]
