import { C, S, lv, dp } from './shared'

export const mageChainSkills = [
  // ── Mage (10) ──
  { _id: S.sp_recovery, class_id: C.mage, name: 'Aumentar Recuperação de SP', slug: 'increase-sp-recovery', type: 'passive' as const, max_level: 10, description: 'Aumenta recuperação natural de SP.', prerequisites: [], icon_url: 'https://browiki.org/images/2/2f/Aumentar_Recupera%C3%A7%C3%A3o_de_SP.png', position: { x: 0, y: 0 }, levels: lv(10, [0]) },
  { _id: S.napalm_beat, class_id: C.mage, name: 'Espíritos Anciões', slug: 'napalm-beat', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Ataque fantasma em área.', prerequisites: [], icon_url: 'https://browiki.org/images/4/49/Esp%C3%ADritos_Anci%C3%B5es.png', position: { x: 0, y: 2 }, levels: lv(10, [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]) },
  { _id: S.soul_strike, class_id: C.mage, name: 'Ataque Espiritual', slug: 'soul-strike', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Projéteis fantasma no inimigo.', prerequisites: [], icon_url: 'https://browiki.org/images/1/15/Ataque_Espiritual.png', position: { x: 1, y: 2 }, levels: lv(10, [18, 14, 24, 20, 30, 26, 36, 32, 42, 38]) },
  { _id: S.cold_bolt, class_id: C.mage, name: 'Lanças de Gelo', slug: 'cold-bolt', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Projéteis de gelo no inimigo.', prerequisites: [], icon_url: 'https://browiki.org/images/c/ca/Lan%C3%A7as_de_Gelo.png', position: { x: 2, y: 0 }, levels: lv(10, [12, 14, 16, 18, 20, 22, 24, 26, 28, 30]) },
  { _id: S.frost_diver, class_id: C.mage, name: 'Rajada Congelante', slug: 'frost-diver', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Congela o inimigo.', prerequisites: [{ skill_id: S.cold_bolt, required_level: 5 }], icon_url: 'https://browiki.org/images/0/0c/Rajada_Congelante.png', position: { x: 2, y: 2 }, levels: lv(10, [25, 24, 23, 22, 21, 20, 19, 18, 17, 16]) },
  { class_id: C.mage, name: 'Petrificar', slug: 'stone-curse', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Petrifica o inimigo.', prerequisites: [], icon_url: 'https://browiki.org/images/6/65/Petrificar.png', position: { x: 3, y: 0 }, levels: lv(10, [25, 24, 23, 22, 21, 20, 19, 18, 17, 16]) },
  { _id: S.fire_ball, class_id: C.mage, name: 'Bolas de Fogo', slug: 'fire-ball', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Bola de fogo em área.', prerequisites: [], icon_url: 'https://browiki.org/images/5/51/Bolas_de_Fogo.png', position: { x: 1, y: 0 }, levels: lv(10, [25, 25, 25, 25, 25, 25, 25, 25, 25, 25]) },
  { _id: S.fire_bolt, class_id: C.mage, name: 'Lanças de Fogo', slug: 'fire-bolt', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Projéteis de fogo no inimigo.', prerequisites: [], icon_url: 'https://browiki.org/images/4/48/Lan%C3%A7as_de_Fogo.png', position: { x: 4, y: 0 }, levels: lv(10, [12, 14, 16, 18, 20, 22, 24, 26, 28, 30]) },
  { _id: S.lightning_bolt, class_id: C.mage, name: 'Relâmpago', slug: 'lightning-bolt', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Projéteis de raio no inimigo.', prerequisites: [], icon_url: 'https://browiki.org/images/2/27/Rel%C3%A2mpago.png', position: { x: 4, y: 2 }, levels: lv(10, [12, 14, 16, 18, 20, 22, 24, 26, 28, 30]) },
  { _id: S.thunderstorm, class_id: C.mage, name: 'Tempestade de Raios', slug: 'thunderstorm', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Tempestade de raios em área.', prerequisites: [{ skill_id: S.lightning_bolt, required_level: 5 }], icon_url: 'https://browiki.org/images/f/f2/Tempestade_de_Raios.png', position: { x: 4, y: 4 }, levels: lv(10, [29, 29, 29, 29, 29, 29, 29, 29, 29, 29]) },

  // ── Wizard (8) ──
  { _id: S.jupitel_thunder, class_id: C.wizard, name: 'Trovão de Júpiter', slug: 'jupitel-thunder', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Raio poderoso que empurra o inimigo.', prerequisites: [{ skill_id: S.lightning_bolt, required_level: 3 }], icon_url: 'https://browiki.org/images/e/ef/Trov%C3%A3o_de_J%C3%BApiter.png', position: { x: 0, y: 0 }, levels: lv(10, [20, 23, 26, 29, 32, 35, 38, 41, 44, 47]) },
  { class_id: C.wizard, name: 'Ira de Thor', slug: 'lord-of-vermillion', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Tempestade elétrica devastadora.', prerequisites: [{ skill_id: S.jupitel_thunder, required_level: 5 }], icon_url: 'https://browiki.org/images/e/e9/Ira_de_Thor.png', position: { x: 0, y: 2 }, levels: lv(10, [60, 64, 68, 72, 76, 80, 84, 88, 92, 96]) },
  { class_id: C.wizard, name: "Esfera d'Água", slug: 'water-ball', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Projéteis de água (requer estar na água).', prerequisites: [], icon_url: "https://browiki.org/images/4/4f/Esfera_d%27%C3%81gua.png", position: { x: 1, y: 0 }, levels: lv(5, [15, 20, 20, 25, 25]) },
  { class_id: C.wizard, name: 'Chuva de Meteoros', slug: 'meteor-storm', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Chuva de meteoros em área.', prerequisites: [], icon_url: 'https://browiki.org/images/6/6b/Chuva_de_Meteoros.png', position: { x: 2, y: 0 }, levels: lv(10, [20, 24, 28, 32, 36, 40, 44, 48, 52, 56]) },
  { class_id: C.wizard, name: 'Nevasca', slug: 'storm-gust', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Nevasca que congela inimigos em área.', prerequisites: [], icon_url: 'https://browiki.org/images/b/b5/Nevasca.png', position: { x: 3, y: 0 }, levels: lv(10, [78, 78, 78, 78, 78, 78, 78, 78, 78, 78]) },
  { class_id: C.wizard, name: 'Fúria da Terra', slug: 'heavens-drive', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Pilares de terra que atingem área.', prerequisites: [], icon_url: 'https://browiki.org/images/9/9a/F%C3%BAria_da_Terra.png', position: { x: 3, y: 2 }, levels: lv(10, [28, 32, 36, 40, 44, 48, 52, 56, 60, 64]) },
  { class_id: C.wizard, name: 'Pântano dos Mortos', slug: 'quagmire', type: 'support' as const, max_level: 10, target: 'area' as const, description: 'Reduz AGI e DEX dos inimigos na área.', prerequisites: [], icon_url: 'https://browiki.org/images/0/08/P%C3%A2ntano_dos_Mortos.png', position: { x: 4, y: 0 }, levels: lv(10, [5, 10, 15, 20, 25, 30, 35, 40, 45, 50]) },
  { class_id: C.wizard, name: 'Sentido Sobrenatural', slug: 'sense', type: 'active' as const, max_level: 1, target: 'enemy' as const, description: 'Revela informações do monstro.', prerequisites: [], icon_url: 'https://browiki.org/images/b/b0/Sentido_Sobrenatural.png', position: { x: 4, y: 2 }, levels: lv(1, [10]) },

  // ── Sage (8) ──
  { class_id: C.sage, name: 'Conjuração Livre', slug: 'free-cast', type: 'passive' as const, max_level: 10, description: 'Permite mover enquanto conjura.', prerequisites: [], icon_url: 'https://browiki.org/images/b/b2/Conjura%C3%A7%C3%A3o_Livre.png', position: { x: 0, y: 0 }, levels: lv(10, [0]) },
  { class_id: C.sage, name: 'Desejo Arcano', slug: 'auto-spell', type: 'passive' as const, max_level: 10, description: 'Chance de auto-conjurar ao atacar.', prerequisites: [], icon_url: 'https://browiki.org/images/b/bf/Desejo_Arcano.png', position: { x: 1, y: 0 }, levels: lv(10, [0]) },
  { class_id: C.sage, name: 'Cancelar Magia', slug: 'cast-cancel', type: 'active' as const, max_level: 5, target: 'self' as const, description: 'Cancela a própria conjuração.', prerequisites: [], icon_url: 'https://browiki.org/images/3/35/Cancelar_Magia.png', position: { x: 0, y: 2 }, levels: lv(5, [2, 2, 2, 2, 2]) },
  { class_id: C.sage, name: 'Desconcentrar', slug: 'spell-breaker', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Interrompe conjuração do inimigo.', prerequisites: [], icon_url: 'https://browiki.org/images/c/ce/Desconcentrar.png', position: { x: 2, y: 0 }, levels: lv(10, [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]) },
  { class_id: C.sage, name: 'Espelho Mágico', slug: 'magic-rod', type: 'active' as const, max_level: 10, target: 'self' as const, description: 'Absorve magia inimiga como SP.', prerequisites: [], icon_url: 'https://browiki.org/images/b/b8/Espelho_M%C3%A1gico.png', position: { x: 3, y: 0 }, levels: lv(10, [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]) },
  { class_id: C.sage, name: 'Desencantar', slug: 'dispell', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Remove buffs do alvo.', prerequisites: [], icon_url: 'https://browiki.org/images/3/37/Desencantar.png', position: { x: 2, y: 2 }, levels: lv(5, [1, 1, 1, 1, 1]) },
  { class_id: C.sage, name: 'Proteger Terreno', slug: 'land-protector', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Cria zona que anula magias de área.', prerequisites: [], icon_url: 'https://browiki.org/images/0/0f/Proteger_Terreno.png', position: { x: 4, y: 0 }, levels: lv(5, [66, 66, 66, 66, 66]) },
  { class_id: C.sage, name: 'Abracadabra', slug: 'abracadabra', type: 'active' as const, max_level: 10, target: 'self' as const, description: 'Efeito aleatório poderoso.', prerequisites: [], icon_url: 'https://browiki.org/images/a/a0/Abracadabra.png', position: { x: 4, y: 2 }, levels: lv(10, [50, 50, 50, 50, 50, 50, 50, 50, 50, 50]) },

  // ── High Wizard (6) ──
  { class_id: C.high_wizard, name: 'Amplificação Mística', slug: 'mystical-amplification', type: 'buff' as const, max_level: 10, target: 'self' as const, description: 'Aumenta poder mágico da próxima skill.', prerequisites: [], icon_url: 'https://browiki.org/images/5/5d/Amplifica%C3%A7%C3%A3o_M%C3%ADstica.png', position: { x: 0, y: 0 }, levels: lv(10, [14, 14, 14, 14, 14, 14, 14, 14, 14, 14]) },
  { class_id: C.high_wizard, name: 'Vulcão Napalm', slug: 'napalm-vulcan', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Napalm Beat versão transcendente.', prerequisites: [], icon_url: 'https://browiki.org/images/0/0c/Vulc%C3%A3o_Napalm.png', position: { x: 1, y: 0 }, levels: lv(5, [40, 45, 50, 55, 60]) },
  { class_id: C.high_wizard, name: 'Campo Gravitacional', slug: 'gravitation-field', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Campo gravitacional que causa dano.', prerequisites: [], icon_url: 'https://browiki.org/images/2/23/Campo_Gravitacional.png', position: { x: 2, y: 0 }, levels: lv(5, [20, 40, 60, 80, 100]) },
  { class_id: C.high_wizard, name: 'Ganbantein', slug: 'ganbantein', type: 'active' as const, max_level: 1, target: 'area' as const, description: 'Remove todas as magias de área.', prerequisites: [], icon_url: 'https://browiki.org/images/6/68/Ganbantein.png', position: { x: 3, y: 0 }, levels: lv(1, [40]) },
  { class_id: C.high_wizard, name: 'Esmagamento Mágico', slug: 'stave-crasher', type: 'active' as const, max_level: 1, target: 'enemy' as const, description: 'Ataque com cajado baseado em MATK.', prerequisites: [], icon_url: 'https://browiki.org/images/5/50/Esmagamento_M%C3%A1gico.png', position: { x: 4, y: 0 }, levels: lv(1, [8]) },
  { class_id: C.high_wizard, name: 'Dreno de Alma', slug: 'amplify-magic-power', type: 'buff' as const, max_level: 10, target: 'self' as const, description: 'Aumenta MATK temporariamente.', prerequisites: [], icon_url: 'https://browiki.org/images/4/47/Dreno_de_Alma.png', position: { x: 0, y: 2 }, levels: lv(10, [10, 14, 18, 22, 26, 30, 34, 38, 42, 46]) },

  // ── Scholar (6) ──
  { class_id: C.scholar, name: 'Lanças Duplas', slug: 'double-casting', type: 'passive' as const, max_level: 5, description: 'Chance de conjurar duas vezes.', prerequisites: [], icon_url: 'https://browiki.org/images/8/8c/Lan%C3%A7as_Duplas.png', position: { x: 0, y: 0 }, levels: lv(5, [0]) },
  { class_id: C.scholar, name: 'Presciência', slug: 'spell-fist', type: 'active' as const, max_level: 5, target: 'self' as const, description: 'Infunde magia nos punhos.', prerequisites: [], icon_url: 'https://browiki.org/images/1/1e/Presci%C3%AAncia.png', position: { x: 1, y: 0 }, levels: lv(5, [40, 44, 48, 52, 56]) },
  { class_id: C.scholar, name: 'Indulgir', slug: 'indulge', type: 'active' as const, max_level: 5, target: 'ally' as const, description: 'Transfere SP para um aliado.', prerequisites: [], icon_url: 'https://browiki.org/images/d/d3/Indulgir.png', position: { x: 2, y: 0 }, levels: lv(5, [10, 10, 10, 10, 10]) },
  { class_id: C.scholar, name: 'Exalar Alma', slug: 'foresight', type: 'buff' as const, max_level: 1, target: 'self' as const, description: 'Dispensa reagentes de magias.', prerequisites: [], icon_url: 'https://browiki.org/images/b/b0/Exalar_Alma.png', position: { x: 3, y: 0 }, levels: lv(1, [80]) },
  { class_id: C.scholar, name: 'Bruma Ofuscante', slug: 'blinding-mist', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Cria névoa que cega inimigos.', prerequisites: [], icon_url: 'https://browiki.org/images/4/4e/Bruma_Ofuscante.png', position: { x: 4, y: 0 }, levels: lv(5, [22, 24, 26, 28, 30]) },
  { class_id: C.scholar, name: 'Estudo de Livros', slug: 'free-research', type: 'passive' as const, max_level: 5, description: 'Aumenta MAX SP e redução de cast.', prerequisites: [], icon_url: 'https://browiki.org/images/6/6b/Estudo_de_Livros.png', position: { x: 0, y: 2 }, levels: lv(5, [0]) },

  // ── Arcane Master (6) ──
  { class_id: C.arcane_master, name: 'Tetra Vortex', slug: 'tetra-vortex', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Ataque dos 4 elementos combinados.', prerequisites: [], icon_url: 'https://browiki.org/images/e/e0/Tetra_Vortex.png', position: { x: 0, y: 0 }, levels: lv(5, [120, 150, 180, 210, 240]) },
  { class_id: C.arcane_master, name: 'Cometa', slug: 'comet', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Invoca um cometa devastador.', prerequisites: [], icon_url: 'https://browiki.org/images/c/cc/Cometa.png', position: { x: 1, y: 0 }, levels: lv(5, [480, 560, 640, 720, 800]) },
  { class_id: C.arcane_master, name: 'Zero Absoluto', slug: 'diamondstorm', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Tempestade de cristais de gelo.', prerequisites: [], icon_url: 'https://browiki.org/images/2/2e/Zero_Absoluto.png', position: { x: 2, y: 0 }, levels: lv(5, [50, 60, 70, 80, 90]) },
  { class_id: C.arcane_master, name: 'Corrente Elétrica', slug: 'chain-lightning', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Raio que pula entre inimigos.', prerequisites: [], icon_url: 'https://browiki.org/images/3/32/Corrente_El%C3%A9trica.png', position: { x: 3, y: 0 }, levels: lv(5, [80, 90, 100, 110, 120]) },
  { class_id: C.arcane_master, name: 'Meteoro Escarlate', slug: 'crimson-rock', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Meteoro de fogo concentrado.', prerequisites: [], icon_url: 'https://browiki.org/images/9/9e/Meteoro_Escarlate.png', position: { x: 4, y: 0 }, levels: lv(5, [60, 70, 80, 90, 100]) },
  { class_id: C.arcane_master, name: 'Esquife de Gelo', slug: 'jack-frost', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Congela toda a área ao redor.', prerequisites: [], icon_url: 'https://browiki.org/images/7/76/Esquife_de_Gelo.png', position: { x: 4, y: 2 }, levels: lv(5, [50, 60, 70, 80, 90]) },

  // ── Sorcerer (6) ──
  { class_id: C.sorcerer, name: 'Onda Psíquica', slug: 'psychic-wave', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Onda psíquica em grande área.', prerequisites: [], icon_url: 'https://browiki.org/images/8/83/Onda_Ps%C3%ADquica.png', position: { x: 0, y: 0 }, levels: lv(10, [48, 52, 56, 60, 64, 68, 72, 76, 80, 84]) },
  { class_id: C.sorcerer, name: 'Encanto de Órion', slug: 'striking', type: 'support' as const, max_level: 5, target: 'ally' as const, description: 'Aumenta ATK e chance de crítico de um aliado.', prerequisites: [], icon_url: 'https://browiki.org/images/f/fb/Encanto_de_%C3%93rion.png', position: { x: 1, y: 0 }, levels: lv(5, [10, 12, 14, 16, 18]) },
  { class_id: C.sorcerer, name: 'Lanças dos Aesir', slug: 'varetyr-spear', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Lança elemental de trovão.', prerequisites: [], icon_url: 'https://browiki.org/images/d/d8/Lan%C3%A7as_dos_Aesir.png', position: { x: 2, y: 0 }, levels: lv(5, [55, 62, 69, 76, 83]) },
  { class_id: C.sorcerer, name: 'Pó de Diamante', slug: 'diamond-dust', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Poeira de diamante que congela.', prerequisites: [], icon_url: 'https://browiki.org/images/e/ec/P%C3%B3_de_Diamante.png', position: { x: 3, y: 0 }, levels: lv(5, [50, 56, 62, 68, 74]) },
  { class_id: C.sorcerer, name: 'Tornado', slug: 'ball-lightning', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Esfera elétrica em área.', prerequisites: [], icon_url: 'https://browiki.org/images/4/40/Tornado.png', position: { x: 4, y: 0 }, levels: lv(5, [60, 68, 76, 84, 92]) },
  { class_id: C.sorcerer, name: 'Domínio Elemental', slug: 'elemental-control', type: 'active' as const, max_level: 4, target: 'self' as const, description: 'Controla elementais invocados.', prerequisites: [], icon_url: 'https://browiki.org/images/2/26/Dom%C3%ADnio_Elemental.png', position: { x: 4, y: 2 }, levels: lv(4, [40, 50, 60, 70]) },
]
