import { C, S, lv, dp } from './shared'

export const merchantChainSkills = [
  // ── Merchant (8) ──
  { _id: S.discount, class_id: C.merchant, name: 'Discount', slug: 'discount', type: 'passive' as const, max_level: 10, description: 'Reduz preço de compra em NPC.', prerequisites: [], icon_url: dp(41), position: { x: 0, y: 0 }, levels: lv(10, [0]) },
  { _id: S.overcharge, class_id: C.merchant, name: 'Overcharge', slug: 'overcharge', type: 'passive' as const, max_level: 10, description: 'Aumenta preço de venda em NPC.', prerequisites: [], icon_url: dp(42), position: { x: 1, y: 0 }, levels: lv(10, [0]) },
  { class_id: C.merchant, name: 'Enlarge Weight Limit', slug: 'enlarge-weight-limit', type: 'passive' as const, max_level: 10, description: 'Aumenta capacidade de peso.', prerequisites: [], icon_url: dp(37), position: { x: 2, y: 0 }, levels: lv(10, [0]) },
  { _id: S.pushcart, class_id: C.merchant, name: 'Pushcart', slug: 'pushcart', type: 'passive' as const, max_level: 5, description: 'Permite usar carrinho.', prerequisites: [], icon_url: dp(38), position: { x: 3, y: 0 }, levels: lv(5, [0]) },
  { _id: S.vending, class_id: C.merchant, name: 'Vending', slug: 'vending', type: 'active' as const, max_level: 4, target: 'self' as const, description: 'Abre uma loja para vender itens.', prerequisites: [{ skill_id: S.pushcart, required_level: 2 }], icon_url: dp(39), position: { x: 3, y: 2 }, levels: lv(4, [30, 30, 30, 30]) },
  { class_id: C.merchant, name: 'Mammonite', slug: 'mammonite', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Ataque poderoso que custa zeny.', prerequisites: [], icon_url: dp(40), position: { x: 4, y: 0 }, levels: lv(10, [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]) },
  { class_id: C.merchant, name: 'Change Cart', slug: 'change-cart', type: 'active' as const, max_level: 4, target: 'self' as const, description: 'Muda aparência do carrinho.', prerequisites: [], icon_url: dp(154), position: { x: 4, y: 2 }, levels: lv(4, [0, 0, 0, 0]) },
  { class_id: C.merchant, name: 'Item Appraisal', slug: 'item-appraisal', type: 'active' as const, max_level: 1, target: 'self' as const, description: 'Identifica itens desconhecidos.', prerequisites: [], icon_url: dp(36), position: { x: 1, y: 2 }, levels: lv(1, [10]) },

  // ── Blacksmith (8) ──
  { class_id: C.blacksmith, name: 'Adrenaline Rush', slug: 'adrenaline-rush', type: 'buff' as const, max_level: 5, target: 'area' as const, description: 'Aumenta ASPD com armas de impacto.', prerequisites: [], icon_url: dp(111), position: { x: 0, y: 0 }, levels: lv(5, [20, 20, 20, 20, 20]) },
  { class_id: C.blacksmith, name: 'Weapon Perfection', slug: 'weapon-perfection', type: 'buff' as const, max_level: 5, target: 'self' as const, description: 'Remove penalidade de tamanho.', prerequisites: [], icon_url: dp(112), position: { x: 1, y: 0 }, levels: lv(5, [18, 18, 18, 18, 18]) },
  { class_id: C.blacksmith, name: 'Maximize Power', slug: 'maximize-power', type: 'buff' as const, max_level: 5, target: 'self' as const, description: 'ATK sempre no valor máximo.', prerequisites: [], icon_url: dp(113), position: { x: 2, y: 0 }, levels: lv(5, [10, 10, 10, 10, 10]) },
  { class_id: C.blacksmith, name: 'Power Thrust', slug: 'power-thrust', type: 'buff' as const, max_level: 5, target: 'area' as const, description: 'Aumenta ATK do grupo (pode quebrar arma).', prerequisites: [], icon_url: dp(114), position: { x: 3, y: 0 }, levels: lv(5, [12, 12, 12, 12, 12]) },
  { class_id: C.blacksmith, name: 'Hammerfall', slug: 'hammerfall', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Atordoa inimigos em área.', prerequisites: [], icon_url: dp(110), position: { x: 4, y: 0 }, levels: lv(5, [10, 10, 10, 10, 10]) },
  { class_id: C.blacksmith, name: 'Skin Tempering', slug: 'skin-tempering', type: 'passive' as const, max_level: 5, description: 'Resistência a fogo e neutro.', prerequisites: [], icon_url: dp(115), position: { x: 0, y: 2 }, levels: lv(5, [0]) },
  { class_id: C.blacksmith, name: 'Hilt Binding', slug: 'hilt-binding', type: 'passive' as const, max_level: 1, description: 'Aumenta ATK.', prerequisites: [], icon_url: dp(109), position: { x: 1, y: 2 }, levels: lv(1, [0]) },
  { class_id: C.blacksmith, name: 'Enchantedstone Craft', slug: 'enchantedstone-craft', type: 'active' as const, max_level: 5, target: 'self' as const, description: 'Cria pedras elementais.', prerequisites: [], icon_url: dp(108), position: { x: 4, y: 2 }, levels: lv(5, [30, 30, 30, 30, 30]) },

  // ── Alchemist (8) ──
  { class_id: C.alchemist, name: 'Pharmacy', slug: 'pharmacy', type: 'active' as const, max_level: 10, target: 'self' as const, description: 'Cria poções e itens alquímicos.', prerequisites: [], icon_url: dp(228), position: { x: 0, y: 0 }, levels: lv(10, [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]) },
  { class_id: C.alchemist, name: 'Potion Pitcher', slug: 'potion-pitcher', type: 'active' as const, max_level: 5, target: 'ally' as const, description: 'Arremessa poção para curar aliado.', prerequisites: [], icon_url: dp(229), position: { x: 1, y: 0 }, levels: lv(5, [1, 1, 1, 1, 1]) },
  { class_id: C.alchemist, name: 'Aid Potion', slug: 'aid-potion', type: 'active' as const, max_level: 5, target: 'ally' as const, description: 'Usa poção em aliado à distância.', prerequisites: [], icon_url: dp(230), position: { x: 2, y: 0 }, levels: lv(5, [10, 10, 10, 10, 10]) },
  { class_id: C.alchemist, name: 'Bioethics', slug: 'bioethics', type: 'passive' as const, max_level: 1, description: 'Permite criar homúnculos.', prerequisites: [], icon_url: dp(231), position: { x: 3, y: 0 }, levels: lv(1, [0]) },
  { class_id: C.alchemist, name: 'Acid Terror', slug: 'acid-terror', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Ataque ácido que pode quebrar armadura.', prerequisites: [], icon_url: dp(232), position: { x: 4, y: 0 }, levels: lv(10, [15, 15, 15, 15, 15, 15, 15, 15, 15, 15]) },
  { class_id: C.alchemist, name: 'Bomb', slug: 'bomb', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Arremessa bomba de garrafa.', prerequisites: [], icon_url: dp(233), position: { x: 4, y: 2 }, levels: lv(5, [10, 10, 10, 10, 10]) },
  { class_id: C.alchemist, name: 'Demonstration', slug: 'demonstration', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Cria fogo no chão que queima.', prerequisites: [], icon_url: dp(234), position: { x: 3, y: 2 }, levels: lv(5, [10, 10, 10, 10, 10]) },
  { class_id: C.alchemist, name: 'Berserk Pitcher', slug: 'berserk-pitcher', type: 'active' as const, max_level: 5, target: 'ally' as const, description: 'Arremessa garrafa de berserk potion.', prerequisites: [], icon_url: dp(235), position: { x: 0, y: 2 }, levels: lv(5, [10, 10, 10, 10, 10]) },

  // ── Whitesmith (5) ──
  { class_id: C.whitesmith, name: 'Cart Boost', slug: 'cart-boost', type: 'buff' as const, max_level: 5, target: 'self' as const, description: 'Aumenta velocidade com carrinho.', prerequisites: [], icon_url: dp(386), position: { x: 0, y: 0 }, levels: lv(5, [12, 12, 12, 12, 12]) },
  { class_id: C.whitesmith, name: 'Full Adrenaline Rush', slug: 'full-adrenaline-rush', type: 'buff' as const, max_level: 5, target: 'area' as const, description: 'Adrenaline Rush para todas as armas.', prerequisites: [], icon_url: dp(387), position: { x: 1, y: 0 }, levels: lv(5, [36, 36, 36, 36, 36]) },
  { class_id: C.whitesmith, name: 'Meltdown', slug: 'meltdown', type: 'active' as const, max_level: 10, target: 'self' as const, description: 'Chance de quebrar equipamento do alvo.', prerequisites: [], icon_url: dp(388), position: { x: 2, y: 0 }, levels: lv(10, [50, 50, 50, 50, 50, 50, 50, 50, 50, 50]) },
  { class_id: C.whitesmith, name: 'Maximum Over Thrust', slug: 'maximum-over-thrust', type: 'buff' as const, max_level: 5, target: 'self' as const, description: 'Aumenta ATK massivamente.', prerequisites: [], icon_url: dp(389), position: { x: 3, y: 0 }, levels: lv(5, [15, 15, 15, 15, 15]) },
  { class_id: C.whitesmith, name: 'Weapon Repair', slug: 'weapon-repair', type: 'active' as const, max_level: 5, target: 'ally' as const, description: 'Repara equipamento quebrado.', prerequisites: [], icon_url: dp(390), position: { x: 4, y: 0 }, levels: lv(5, [30, 30, 30, 30, 30]) },

  // ── Mechanic (6) ──
  { class_id: C.mechanic, name: 'Power Swing', slug: 'power-swing', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Golpe pesado com mecha.', prerequisites: [], icon_url: dp(2253), position: { x: 0, y: 0 }, levels: lv(5, [18, 22, 26, 30, 34]) },
  { class_id: C.mechanic, name: 'Arm Cannon', slug: 'arm-cannon', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Dispara canhão do braço mecha.', prerequisites: [], icon_url: dp(2254), position: { x: 1, y: 0 }, levels: lv(5, [30, 36, 42, 48, 54]) },
  { class_id: C.mechanic, name: 'Ice Launcher', slug: 'ice-launcher', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Lança gelo que congela inimigos.', prerequisites: [], icon_url: dp(2255), position: { x: 2, y: 0 }, levels: lv(5, [30, 34, 38, 42, 46]) },
  { class_id: C.mechanic, name: 'Vulcan Arm', slug: 'vulcan-arm', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Rajada de tiros do braço.', prerequisites: [], icon_url: dp(2256), position: { x: 3, y: 0 }, levels: lv(5, [2, 2, 2, 2, 2]) },
  { class_id: C.mechanic, name: 'Pile Bunker', slug: 'pile-bunker', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Golpe devastador com pilão.', prerequisites: [], icon_url: dp(2257), position: { x: 4, y: 0 }, levels: lv(5, [50, 50, 50, 50, 50]) },
  { class_id: C.mechanic, name: 'Madogear License', slug: 'madogear-license', type: 'passive' as const, max_level: 5, description: 'Permite pilotar Madogear.', prerequisites: [], icon_url: dp(2258), position: { x: 0, y: 2 }, levels: lv(5, [0]) },

  // ── Creator (6) ──
  { class_id: C.creator, name: 'Acid Demonstration', slug: 'acid-demonstration', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Combina ácido + bomba para dano baseado em VIT.', prerequisites: [], icon_url: dp(235), position: { x: 0, y: 0 }, levels: lv(10, [30, 30, 30, 30, 30, 30, 30, 30, 30, 30]) },
  { class_id: C.creator, name: 'Call Homunculus', slug: 'call-homunculus', type: 'active' as const, max_level: 1, target: 'self' as const, description: 'Invoca o homúnculo.', prerequisites: [], icon_url: dp(236), position: { x: 1, y: 0 }, levels: lv(1, [10]) },
  { class_id: C.creator, name: 'Homunculus Resurrection', slug: 'homunculus-resurrection', type: 'active' as const, max_level: 5, target: 'self' as const, description: 'Revive o homúnculo.', prerequisites: [], icon_url: dp(237), position: { x: 2, y: 0 }, levels: lv(5, [10, 10, 10, 10, 10]) },
  { class_id: C.creator, name: 'Bio Explosion', slug: 'bio-explosion', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Explosão biológica em área.', prerequisites: [], icon_url: dp(396), position: { x: 3, y: 0 }, levels: lv(5, [20, 24, 28, 32, 36]) },
  { class_id: C.creator, name: 'Marine Sphere', slug: 'marine-sphere', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Invoca esferas marinhas que explodem.', prerequisites: [], icon_url: dp(238), position: { x: 4, y: 0 }, levels: lv(5, [10, 10, 10, 10, 10]) },
  { class_id: C.creator, name: 'Twilight Pharmacy', slug: 'twilight-pharmacy', type: 'active' as const, max_level: 3, target: 'self' as const, description: 'Produção em massa de poções.', prerequisites: [], icon_url: dp(397), position: { x: 4, y: 2 }, levels: lv(3, [200, 200, 200]) },

  // ── Genetic (6) ──
  { class_id: C.genetic, name: 'Fire Expansion', slug: 'fire-expansion', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Expande fogo com efeitos variados.', prerequisites: [], icon_url: dp(2478), position: { x: 0, y: 0 }, levels: lv(5, [30, 36, 42, 48, 54]) },
  { class_id: C.genetic, name: 'Acid Bomb', slug: 'acid-bomb', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Versão melhorada de Acid Demonstration.', prerequisites: [], icon_url: dp(2479), position: { x: 1, y: 0 }, levels: lv(10, [30, 30, 30, 30, 30, 30, 30, 30, 30, 30]) },
  { class_id: C.genetic, name: "Hell's Plant", slug: 'hells-plant', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Planta carnívora que ataca inimigos.', prerequisites: [], icon_url: dp(2480), position: { x: 2, y: 0 }, levels: lv(5, [20, 24, 28, 32, 36]) },
  { class_id: C.genetic, name: 'Crazy Weed', slug: 'crazy-weed', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Ervas daninhas que removem traps e dano.', prerequisites: [], icon_url: dp(2481), position: { x: 3, y: 0 }, levels: lv(5, [18, 22, 26, 30, 34]) },
  { class_id: C.genetic, name: 'Howling of Mandragora', slug: 'howling-of-mandragora', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Grito que drena SP e causa status.', prerequisites: [], icon_url: dp(2482), position: { x: 4, y: 0 }, levels: lv(5, [40, 44, 48, 52, 56]) },
  { class_id: C.genetic, name: 'Spore Explosion', slug: 'spore-explosion', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Esporos que explodem em cadeia.', prerequisites: [], icon_url: dp(2483), position: { x: 4, y: 2 }, levels: lv(5, [24, 28, 32, 36, 40]) },
]
