import { C, S, lv, dp } from './shared'

export const archerChainSkills = [
  // ── Archer (6) ──
  { _id: S.owls_eye, class_id: C.archer, name: 'Olhos de Coruja', slug: 'owls-eye', type: 'passive' as const, max_level: 10, description: 'Aumenta DEX.', prerequisites: [], icon_url: 'https://browiki.org/images/1/1b/Olhos_de_Coruja.png', position: { x: 0, y: 0 }, levels: lv(10, [0]) },
  { _id: S.vultures_eye, class_id: C.archer, name: 'Olhos de Águia', slug: 'vultures-eye', type: 'passive' as const, max_level: 10, description: 'Aumenta alcance e HIT com arco.', prerequisites: [], icon_url: 'https://browiki.org/images/b/bc/Olhos_de_%C3%81guia.png', position: { x: 2, y: 0 }, levels: lv(10, [0]) },
  { _id: S.improve_concentration, class_id: C.archer, name: 'Concentrar', slug: 'improve-concentration', type: 'buff' as const, max_level: 10, target: 'self' as const, description: 'Aumenta AGI e DEX.', prerequisites: [], icon_url: 'https://browiki.org/images/5/52/Concentrar.png', position: { x: 4, y: 0 }, levels: lv(10, [15, 18, 21, 24, 27, 30, 33, 36, 39, 42]) },
  { _id: S.double_strafe, class_id: C.archer, name: 'Rajada de Flechas', slug: 'double-strafe', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Dispara duas flechas seguidas.', prerequisites: [], icon_url: 'https://browiki.org/images/1/1d/Rajada_de_Flechas.png', position: { x: 0, y: 2 }, levels: lv(10, [12, 12, 12, 12, 12, 12, 12, 12, 12, 12]) },
  { _id: S.arrow_shower, class_id: C.archer, name: 'Chuva de Flechas', slug: 'arrow-shower', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Chuva de flechas em área.', prerequisites: [], icon_url: 'https://browiki.org/images/f/fe/Chuva_de_Flechas.png', position: { x: 2, y: 2 }, levels: lv(10, [15, 15, 15, 15, 15, 15, 15, 15, 15, 15]) },
  { class_id: C.archer, name: 'Disparo Violento', slug: 'arrow-repel', type: 'active' as const, max_level: 1, target: 'enemy' as const, description: 'Empurra inimigo com flecha.', prerequisites: [], icon_url: 'https://browiki.org/images/e/e5/Disparo_Violento.png', position: { x: 4, y: 2 }, levels: lv(1, [15]) },

  // ── Hunter (8) ──
  { _id: S.falcon_mastery, class_id: C.hunter, name: 'Adestrar Ave', slug: 'falcon-mastery', type: 'passive' as const, max_level: 1, description: 'Permite ter um falcão.', prerequisites: [], icon_url: 'https://browiki.org/images/a/a9/Adestrar_Ave.png', position: { x: 0, y: 0 }, levels: lv(1, [0]) },
  { class_id: C.hunter, name: 'Ataque Aéreo', slug: 'blitz-beat', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'O falcão ataca o inimigo.', prerequisites: [{ skill_id: S.falcon_mastery, required_level: 1 }], icon_url: 'https://browiki.org/images/e/ee/Ataque_A%C3%A9reo.png', position: { x: 0, y: 2 }, levels: lv(5, [10, 10, 10, 10, 10]) },
  { class_id: C.hunter, name: 'Garras de Aço', slug: 'true-sight-hunter', type: 'passive' as const, max_level: 10, description: 'Aumenta todos os status.', prerequisites: [], icon_url: 'https://browiki.org/images/1/16/Garras_de_A%C3%A7o.png', position: { x: 1, y: 0 }, levels: lv(10, [0]) },
  { class_id: C.hunter, name: 'Instalar Mina', slug: 'sharp-shooting', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Tiro preciso com alto dano.', prerequisites: [], icon_url: 'https://browiki.org/images/6/66/Instalar_Mina.png', position: { x: 2, y: 0 }, levels: lv(5, [18, 21, 24, 27, 30]) },
  { class_id: C.hunter, name: 'Instalar Armadilha', slug: 'ankle-snare', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Armadilha que prende inimigos.', prerequisites: [], icon_url: 'https://browiki.org/images/e/e5/Instalar_Armadilha.png', position: { x: 3, y: 0 }, levels: lv(5, [12, 12, 12, 12, 12]) },
  { class_id: C.hunter, name: 'Armadilha Explosiva', slug: 'claymore-trap', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Armadilha explosiva de fogo.', prerequisites: [], icon_url: 'https://browiki.org/images/5/5c/Armadilha_Explosiva.png', position: { x: 4, y: 0 }, levels: lv(5, [15, 15, 15, 15, 15]) },
  { class_id: C.hunter, name: 'Flagelo das Feras', slug: 'beast-bane', type: 'passive' as const, max_level: 10, description: 'Dano extra contra Brute e Insect.', prerequisites: [], icon_url: 'https://browiki.org/images/3/3d/Flagelo_das_Feras.png', position: { x: 1, y: 2 }, levels: lv(10, [0]) },
  { class_id: C.hunter, name: 'Remover Armadilha', slug: 'remove-trap', type: 'active' as const, max_level: 1, target: 'area' as const, description: 'Remove armadilha do chão.', prerequisites: [], icon_url: 'https://browiki.org/images/8/87/Remover_Armadilha.png', position: { x: 3, y: 2 }, levels: lv(1, [5]) },

  // ── Bard (7) ──
  { class_id: C.bard, name: 'Lições de Música', slug: 'music-lessons', type: 'passive' as const, max_level: 10, description: 'Aumenta efeito das canções e ATK com instrumento.', prerequisites: [], icon_url: 'https://browiki.org/images/8/8d/Li%C3%A7%C3%B5es_de_M%C3%BAsica.png', position: { x: 0, y: 0 }, levels: lv(10, [0]) },
  { class_id: C.bard, name: 'Flecha Melódica', slug: 'melody-strike', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Ataque musical à distância.', prerequisites: [], icon_url: 'https://browiki.org/images/9/9a/Flecha_Mel%C3%B3dica.png', position: { x: 0, y: 2 }, levels: lv(10, [8, 8, 8, 8, 8, 8, 8, 8, 8, 8]) },
  { class_id: C.bard, name: 'Assovio', slug: 'a-whistle', type: 'buff' as const, max_level: 10, target: 'area' as const, description: 'Aumenta FLEE do grupo.', prerequisites: [], icon_url: 'https://browiki.org/images/9/93/Assovio.png', position: { x: 1, y: 0 }, levels: lv(10, [18, 20, 22, 24, 26, 28, 30, 32, 34, 36]) },
  { class_id: C.bard, name: 'Maçãs de Idun', slug: 'apple-of-idun', type: 'buff' as const, max_level: 10, target: 'area' as const, description: 'Aumenta HP máximo e recuperação.', prerequisites: [], icon_url: 'https://browiki.org/images/1/1a/Ma%C3%A7%C3%A3s_de_Idun.png', position: { x: 2, y: 0 }, levels: lv(10, [40, 42, 44, 46, 48, 50, 52, 54, 56, 58]) },
  { class_id: C.bard, name: 'Poema de Bragi', slug: 'poem-of-bragi', type: 'buff' as const, max_level: 10, target: 'area' as const, description: 'Reduz tempo de conjuração do grupo.', prerequisites: [], icon_url: 'https://browiki.org/images/c/cf/Poema_de_Bragi.png', position: { x: 3, y: 0 }, levels: lv(10, [40, 42, 44, 46, 48, 50, 52, 54, 56, 58]) },
  { class_id: C.bard, name: 'Lamento de Loki', slug: 'lokis-veil', type: 'buff' as const, max_level: 10, target: 'area' as const, description: 'Impede uso de skills na área.', prerequisites: [], icon_url: 'https://browiki.org/images/6/6e/Lamento_de_Loki.png', position: { x: 4, y: 0 }, levels: lv(10, [10, 12, 14, 16, 18, 20, 22, 24, 26, 28]) },
  { class_id: C.bard, name: 'Dissonância', slug: 'dissonance', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Causa dano sonoro em área.', prerequisites: [], icon_url: 'https://browiki.org/images/1/1a/Disson%C3%A2ncia.png', position: { x: 4, y: 2 }, levels: lv(10, [18, 20, 22, 24, 26, 28, 30, 32, 34, 36]) },

  // ── Dancer (7) ──
  { class_id: C.dancer, name: 'Lições de Dança', slug: 'dance-lessons', type: 'passive' as const, max_level: 10, description: 'Aumenta efeito das danças e ATK com chicote.', prerequisites: [], icon_url: 'https://browiki.org/images/f/ff/Li%C3%A7%C3%B5es_de_Dan%C3%A7a.png', position: { x: 0, y: 0 }, levels: lv(10, [0]) },
  { class_id: C.dancer, name: 'Piscadela', slug: 'charming-wink', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Seduz o inimigo brevemente.', prerequisites: [], icon_url: 'https://browiki.org/images/c/c5/Piscadela.png', position: { x: 0, y: 2 }, levels: lv(5, [8, 10, 12, 14, 16]) },
  { class_id: C.dancer, name: 'Dança Cigana', slug: 'lady-luck', type: 'buff' as const, max_level: 10, target: 'area' as const, description: 'Aumenta taxa de crítico do grupo.', prerequisites: [], icon_url: 'https://browiki.org/images/f/f4/Dan%C3%A7a_Cigana.png', position: { x: 1, y: 0 }, levels: lv(10, [18, 20, 22, 24, 26, 28, 30, 32, 34, 36]) },
  { class_id: C.dancer, name: 'Beijo da Sorte', slug: 'fortunes-kiss', type: 'buff' as const, max_level: 10, target: 'area' as const, description: 'Aumenta chance de crítico do grupo.', prerequisites: [], icon_url: 'https://browiki.org/images/e/eb/Beijo_da_Sorte.png', position: { x: 2, y: 0 }, levels: lv(10, [40, 42, 44, 46, 48, 50, 52, 54, 56, 58]) },
  { class_id: C.dancer, name: 'Dança do Ventre', slug: 'slow-grace', type: 'buff' as const, max_level: 10, target: 'area' as const, description: 'Reduz velocidade de ataque dos inimigos.', prerequisites: [], icon_url: 'https://browiki.org/images/b/b5/Dan%C3%A7a_do_Ventre.png', position: { x: 3, y: 0 }, levels: lv(10, [40, 42, 44, 46, 48, 50, 52, 54, 56, 58]) },
  { class_id: C.dancer, name: 'Escândalo', slug: 'hip-shaker', type: 'buff' as const, max_level: 10, target: 'area' as const, description: 'Drena SP dos inimigos na área.', prerequisites: [], icon_url: 'https://browiki.org/images/0/00/Esc%C3%A2ndalo.png', position: { x: 4, y: 0 }, levels: lv(10, [10, 12, 14, 16, 18, 20, 22, 24, 26, 28]) },
  { class_id: C.dancer, name: 'Bis', slug: 'encore', type: 'active' as const, max_level: 1, target: 'self' as const, description: 'Repete a última dança com metade do SP.', prerequisites: [], icon_url: 'https://browiki.org/images/b/ba/Bis.png', position: { x: 4, y: 2 }, levels: lv(1, [1]) },

  // ── Sniper (6) ──
  { class_id: C.sniper, name: 'Visão Real', slug: 'true-sight', type: 'passive' as const, max_level: 10, description: 'Aumenta todos os atributos.', prerequisites: [], icon_url: 'https://browiki.org/images/8/88/Vis%C3%A3o_Real.png', position: { x: 0, y: 0 }, levels: lv(10, [0]) },
  { class_id: C.sniper, name: 'Caminho do Vento', slug: 'wind-walk', type: 'buff' as const, max_level: 10, target: 'area' as const, description: 'Aumenta FLEE e velocidade de movimento.', prerequisites: [], icon_url: 'https://browiki.org/images/d/df/Caminho_do_Vento.png', position: { x: 1, y: 0 }, levels: lv(10, [26, 30, 34, 38, 42, 46, 50, 54, 58, 62]) },
  { class_id: C.sniper, name: 'Tiro Preciso', slug: 'falcon-eyes', type: 'passive' as const, max_level: 10, description: 'Aumenta HIT e dano crítico.', prerequisites: [], icon_url: 'https://browiki.org/images/6/6f/Tiro_Preciso.png', position: { x: 2, y: 0 }, levels: lv(10, [0]) },
  { class_id: C.sniper, name: 'Assalto do Falcão', slug: 'falcon-assault', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Ataque poderoso do falcão.', prerequisites: [], icon_url: 'https://browiki.org/images/6/61/Assalto_do_Falc%C3%A3o.png', position: { x: 3, y: 0 }, levels: lv(5, [30, 34, 38, 42, 46]) },
  { class_id: C.sniper, name: 'Flecha Ilusória', slug: 'arrow-storm-sniper', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Chuva de flechas devastadora.', prerequisites: [], icon_url: 'https://browiki.org/images/5/51/Flecha_Ilus%C3%B3ria.png', position: { x: 4, y: 0 }, levels: lv(10, [36, 38, 40, 42, 44, 46, 48, 50, 52, 54]) },
  { class_id: C.sniper, name: 'Armadilha Atordoante', slug: 'phantasmic-arrow', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Flecha fantasma que empurra.', prerequisites: [], icon_url: 'https://browiki.org/images/a/aa/Armadilha_Atordoante.png', position: { x: 4, y: 2 }, levels: lv(5, [10, 10, 10, 10, 10]) },

  // ── Minstrel (5) ──
  { class_id: C.minstrel, name: 'Ruído Estridente', slug: 'metallic-sound', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Som metálico que causa dano e drena SP.', prerequisites: [], icon_url: 'https://browiki.org/images/a/a9/Ru%C3%ADdo_Estridente.png', position: { x: 0, y: 0 }, levels: lv(5, [64, 68, 72, 76, 80]) },
  { class_id: C.minstrel, name: 'Ritmo Contagiante', slug: 'swing-dance', type: 'buff' as const, max_level: 5, target: 'area' as const, description: 'Aumenta ASPD do grupo.', prerequisites: [], icon_url: 'https://browiki.org/images/8/86/Ritmo_Contagiante.png', position: { x: 1, y: 0 }, levels: lv(5, [42, 46, 50, 54, 58]) },
  { class_id: C.minstrel, name: 'Serenata ao Luar', slug: 'serenade-of-jordi', type: 'buff' as const, max_level: 5, target: 'area' as const, description: 'Cura HP do grupo com música.', prerequisites: [], icon_url: 'https://browiki.org/images/3/3f/Serenata_ao_Luar.png', position: { x: 2, y: 0 }, levels: lv(5, [38, 42, 46, 50, 54]) },
  { class_id: C.minstrel, name: 'Clamor de Batalha', slug: 'march-of-prontera', type: 'buff' as const, max_level: 5, target: 'area' as const, description: 'Aumenta ATK do grupo.', prerequisites: [], icon_url: 'https://browiki.org/images/7/7a/Clamor_de_Batalha.png', position: { x: 3, y: 0 }, levels: lv(5, [46, 50, 54, 58, 62]) },
  { class_id: C.minstrel, name: 'Canção de Alfheim', slug: 'song-of-mana', type: 'buff' as const, max_level: 5, target: 'area' as const, description: 'Regenera SP do grupo.', prerequisites: [], icon_url: 'https://browiki.org/images/1/11/Can%C3%A7%C3%A3o_de_Alfheim.png', position: { x: 4, y: 0 }, levels: lv(5, [50, 54, 58, 62, 66]) },

  // ── Wanderer (5) ──
  { class_id: C.wanderer, name: 'Temporal de Flechas', slug: 'severe-rainstorm', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Chuva de flechas massiva em área.', prerequisites: [], icon_url: 'https://browiki.org/images/4/4c/Temporal_de_Flechas.png', position: { x: 0, y: 0 }, levels: lv(5, [90, 100, 110, 120, 130]) },
  { class_id: C.wanderer, name: 'Faro Aguçado', slug: 'hawkeye', type: 'buff' as const, max_level: 5, target: 'self' as const, description: 'Aumenta alcance e precisão.', prerequisites: [], icon_url: 'https://browiki.org/images/8/8b/Faro_Agu%C3%A7ado.png', position: { x: 1, y: 0 }, levels: lv(5, [20, 24, 28, 32, 36]) },
  { class_id: C.wanderer, name: 'Dança com Lobos', slug: 'dance-with-wargs', type: 'buff' as const, max_level: 5, target: 'area' as const, description: 'Aumenta ATK do grupo com dança.', prerequisites: [], icon_url: 'https://browiki.org/images/e/e9/Dan%C3%A7a_com_Lobos.png', position: { x: 2, y: 0 }, levels: lv(5, [40, 44, 48, 52, 56]) },
  { class_id: C.wanderer, name: 'Ode a Hela', slug: 'valley-of-death', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Vale da morte que danifica inimigos.', prerequisites: [], icon_url: 'https://browiki.org/images/c/c2/Ode_a_Hela.png', position: { x: 3, y: 0 }, levels: lv(5, [36, 40, 44, 48, 52]) },
  { class_id: C.wanderer, name: 'Sibilo de Eir', slug: 'charming-wink-enhanced', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Versão melhorada de Charming Wink.', prerequisites: [], icon_url: 'https://browiki.org/images/f/fe/Sibilo_de_Eir.png', position: { x: 4, y: 0 }, levels: lv(5, [20, 24, 28, 32, 36]) },

  // ── Ranger (6) ──
  { _id: S.warg_mastery, class_id: C.ranger, name: 'Adestrar Worg', slug: 'warg-mastery', type: 'passive' as const, max_level: 1, description: 'Permite ter um warg.', prerequisites: [], icon_url: 'https://browiki.org/images/0/07/Adestrar_Worg.png', position: { x: 0, y: 0 }, levels: lv(1, [0]) },
  { class_id: C.ranger, name: 'Montaria em Worg', slug: 'warg-rider', type: 'passive' as const, max_level: 3, description: 'Permite montar no warg.', prerequisites: [], icon_url: 'https://browiki.org/images/a/ac/Montaria_em_Worg.png', position: { x: 0, y: 2 }, levels: lv(3, [0]) },
  { class_id: C.ranger, name: 'Mordida Feroz', slug: 'warg-bite', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'O warg morde o inimigo.', prerequisites: [{ skill_id: S.warg_mastery, required_level: 1 }], icon_url: 'https://browiki.org/images/f/f8/Mordida_Feroz.png', position: { x: 1, y: 2 }, levels: lv(5, [12, 14, 16, 18, 20]) },
  { class_id: C.ranger, name: 'Tempestade de Flechas', slug: 'arrow-storm', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Tempestade de flechas avançada.', prerequisites: [], icon_url: 'https://browiki.org/images/d/db/Tempestade_de_Flechas.png', position: { x: 2, y: 0 }, levels: lv(10, [30, 34, 38, 42, 46, 50, 54, 58, 62, 66]) },
  { class_id: C.ranger, name: 'Camuflagem', slug: 'camouflage', type: 'buff' as const, max_level: 5, target: 'self' as const, description: 'Fica invisível próximo a paredes.', prerequisites: [], icon_url: 'https://browiki.org/images/c/cc/Camuflagem.png', position: { x: 3, y: 0 }, levels: lv(5, [40, 40, 40, 40, 40]) },
  { class_id: C.ranger, name: 'Disparo Certeiro', slug: 'aimed-bolt', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Tiro certeiro com dano extra em presos.', prerequisites: [], icon_url: 'https://browiki.org/images/b/bc/Disparo_Certeiro.png', position: { x: 4, y: 0 }, levels: lv(10, [20, 24, 28, 32, 36, 40, 44, 48, 52, 56]) },

  // ── Maestro (5) ──
  { class_id: C.maestro, name: 'Ruído Estridente Melhorado', slug: 'metallic-sound-enhanced', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Versão melhorada de Metallic Sound.', prerequisites: [], icon_url: 'https://browiki.org/images/a/a9/Ru%C3%ADdo_Estridente.png', position: { x: 0, y: 0 }, levels: lv(5, [70, 76, 82, 88, 94]) },
  { class_id: C.maestro, name: 'Ritmo Contagiante Melhorado', slug: 'swing-dance-enhanced', type: 'buff' as const, max_level: 5, target: 'area' as const, description: 'Swing Dance com efeito amplificado.', prerequisites: [], icon_url: 'https://browiki.org/images/8/86/Ritmo_Contagiante.png', position: { x: 1, y: 0 }, levels: lv(5, [48, 52, 56, 60, 64]) },
  { class_id: C.maestro, name: 'Serenata ao Luar Melhorada', slug: 'serenade-of-jordi-enhanced', type: 'buff' as const, max_level: 5, target: 'area' as const, description: 'Serenade of Jordi com cura amplificada.', prerequisites: [], icon_url: 'https://browiki.org/images/3/3f/Serenata_ao_Luar.png', position: { x: 2, y: 0 }, levels: lv(5, [44, 48, 52, 56, 60]) },
  { class_id: C.maestro, name: 'Clamor de Batalha Melhorado', slug: 'march-of-prontera-enhanced', type: 'buff' as const, max_level: 5, target: 'area' as const, description: 'March of Prontera com bônus maior.', prerequisites: [], icon_url: 'https://browiki.org/images/7/7a/Clamor_de_Batalha.png', position: { x: 3, y: 0 }, levels: lv(5, [52, 56, 60, 64, 68]) },
  { class_id: C.maestro, name: 'Canção de Alfheim Melhorada', slug: 'song-of-mana-enhanced', type: 'buff' as const, max_level: 5, target: 'area' as const, description: 'Song of Mana com regeneração maior.', prerequisites: [], icon_url: 'https://browiki.org/images/1/11/Can%C3%A7%C3%A3o_de_Alfheim.png', position: { x: 4, y: 0 }, levels: lv(5, [56, 60, 64, 68, 72]) },
]
