import { C, S, lv, dp } from './shared'

export const mageChainSkills = [
  // ── Mage (10) ──
  { _id: S.sp_recovery, class_id: C.mage, name: 'Increase SP Recovery', slug: 'increase-sp-recovery', type: 'passive' as const, max_level: 10, description: 'Aumenta recuperação natural de SP.', prerequisites: [], icon_url: dp(11), position: { x: 0, y: 0 }, levels: lv(10, [0]) },
  { _id: S.napalm_beat, class_id: C.mage, name: 'Napalm Beat', slug: 'napalm-beat', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Ataque fantasma em área.', prerequisites: [], icon_url: dp(12), position: { x: 0, y: 2 }, levels: lv(10, [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]) },
  { _id: S.soul_strike, class_id: C.mage, name: 'Soul Strike', slug: 'soul-strike', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Projéteis fantasma no inimigo.', prerequisites: [], icon_url: dp(13), position: { x: 1, y: 2 }, levels: lv(10, [18, 14, 24, 20, 30, 26, 36, 32, 42, 38]) },
  { _id: S.cold_bolt, class_id: C.mage, name: 'Cold Bolt', slug: 'cold-bolt', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Projéteis de gelo no inimigo.', prerequisites: [], icon_url: dp(14), position: { x: 2, y: 0 }, levels: lv(10, [12, 14, 16, 18, 20, 22, 24, 26, 28, 30]) },
  { _id: S.frost_diver, class_id: C.mage, name: 'Frost Diver', slug: 'frost-diver', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Congela o inimigo.', prerequisites: [{ skill_id: S.cold_bolt, required_level: 5 }], icon_url: dp(15), position: { x: 2, y: 2 }, levels: lv(10, [25, 24, 23, 22, 21, 20, 19, 18, 17, 16]) },
  { class_id: C.mage, name: 'Stone Curse', slug: 'stone-curse', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Petrifica o inimigo.', prerequisites: [], icon_url: dp(16), position: { x: 3, y: 0 }, levels: lv(10, [25, 24, 23, 22, 21, 20, 19, 18, 17, 16]) },
  { _id: S.fire_ball, class_id: C.mage, name: 'Fire Ball', slug: 'fire-ball', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Bola de fogo em área.', prerequisites: [], icon_url: dp(17), position: { x: 1, y: 0 }, levels: lv(10, [25, 25, 25, 25, 25, 25, 25, 25, 25, 25]) },
  { _id: S.fire_bolt, class_id: C.mage, name: 'Fire Bolt', slug: 'fire-bolt', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Projéteis de fogo no inimigo.', prerequisites: [], icon_url: dp(19), position: { x: 4, y: 0 }, levels: lv(10, [12, 14, 16, 18, 20, 22, 24, 26, 28, 30]) },
  { _id: S.lightning_bolt, class_id: C.mage, name: 'Lightning Bolt', slug: 'lightning-bolt', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Projéteis de raio no inimigo.', prerequisites: [], icon_url: dp(20), position: { x: 4, y: 2 }, levels: lv(10, [12, 14, 16, 18, 20, 22, 24, 26, 28, 30]) },
  { _id: S.thunderstorm, class_id: C.mage, name: 'Thunderstorm', slug: 'thunderstorm', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Tempestade de raios em área.', prerequisites: [{ skill_id: S.lightning_bolt, required_level: 5 }], icon_url: dp(21), position: { x: 4, y: 4 }, levels: lv(10, [29, 29, 29, 29, 29, 29, 29, 29, 29, 29]) },

  // ── Wizard (8) ──
  { _id: S.jupitel_thunder, class_id: C.wizard, name: 'Jupitel Thunder', slug: 'jupitel-thunder', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Raio poderoso que empurra o inimigo.', prerequisites: [{ skill_id: S.lightning_bolt, required_level: 3 }], icon_url: dp(84), position: { x: 0, y: 0 }, levels: lv(10, [20, 23, 26, 29, 32, 35, 38, 41, 44, 47]) },
  { class_id: C.wizard, name: 'Lord of Vermillion', slug: 'lord-of-vermillion', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Tempestade elétrica devastadora.', prerequisites: [{ skill_id: S.jupitel_thunder, required_level: 5 }], icon_url: dp(85), position: { x: 0, y: 2 }, levels: lv(10, [60, 64, 68, 72, 76, 80, 84, 88, 92, 96]) },
  { class_id: C.wizard, name: 'Water Ball', slug: 'water-ball', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Projéteis de água (requer estar na água).', prerequisites: [], icon_url: dp(86), position: { x: 1, y: 0 }, levels: lv(5, [15, 20, 20, 25, 25]) },
  { class_id: C.wizard, name: 'Meteor Storm', slug: 'meteor-storm', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Chuva de meteoros em área.', prerequisites: [], icon_url: dp(83), position: { x: 2, y: 0 }, levels: lv(10, [20, 24, 28, 32, 36, 40, 44, 48, 52, 56]) },
  { class_id: C.wizard, name: 'Storm Gust', slug: 'storm-gust', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Nevasca que congela inimigos em área.', prerequisites: [], icon_url: dp(89), position: { x: 3, y: 0 }, levels: lv(10, [78, 78, 78, 78, 78, 78, 78, 78, 78, 78]) },
  { class_id: C.wizard, name: "Heaven's Drive", slug: 'heavens-drive', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Pilares de terra que atingem área.', prerequisites: [], icon_url: dp(90), position: { x: 3, y: 2 }, levels: lv(10, [28, 32, 36, 40, 44, 48, 52, 56, 60, 64]) },
  { class_id: C.wizard, name: 'Quagmire', slug: 'quagmire', type: 'support' as const, max_level: 10, target: 'area' as const, description: 'Reduz AGI e DEX dos inimigos na área.', prerequisites: [], icon_url: dp(91), position: { x: 4, y: 0 }, levels: lv(10, [5, 10, 15, 20, 25, 30, 35, 40, 45, 50]) },
  { class_id: C.wizard, name: 'Sense', slug: 'sense', type: 'active' as const, max_level: 1, target: 'enemy' as const, description: 'Revela informações do monstro.', prerequisites: [], icon_url: dp(92), position: { x: 4, y: 2 }, levels: lv(1, [10]) },

  // ── Sage (8) ──
  { class_id: C.sage, name: 'Free Cast', slug: 'free-cast', type: 'passive' as const, max_level: 10, description: 'Permite mover enquanto conjura.', prerequisites: [], icon_url: dp(276), position: { x: 0, y: 0 }, levels: lv(10, [0]) },
  { class_id: C.sage, name: 'Auto Spell', slug: 'auto-spell', type: 'passive' as const, max_level: 10, description: 'Chance de auto-conjurar ao atacar.', prerequisites: [], icon_url: dp(277), position: { x: 1, y: 0 }, levels: lv(10, [0]) },
  { class_id: C.sage, name: 'Cast Cancel', slug: 'cast-cancel', type: 'active' as const, max_level: 5, target: 'self' as const, description: 'Cancela a própria conjuração.', prerequisites: [], icon_url: dp(278), position: { x: 0, y: 2 }, levels: lv(5, [2, 2, 2, 2, 2]) },
  { class_id: C.sage, name: 'Spell Breaker', slug: 'spell-breaker', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Interrompe conjuração do inimigo.', prerequisites: [], icon_url: dp(279), position: { x: 2, y: 0 }, levels: lv(10, [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]) },
  { class_id: C.sage, name: 'Magic Rod', slug: 'magic-rod', type: 'active' as const, max_level: 10, target: 'self' as const, description: 'Absorve magia inimiga como SP.', prerequisites: [], icon_url: dp(280), position: { x: 3, y: 0 }, levels: lv(10, [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]) },
  { class_id: C.sage, name: 'Dispell', slug: 'dispell', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Remove buffs do alvo.', prerequisites: [], icon_url: dp(289), position: { x: 2, y: 2 }, levels: lv(5, [1, 1, 1, 1, 1]) },
  { class_id: C.sage, name: 'Land Protector', slug: 'land-protector', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Cria zona que anula magias de área.', prerequisites: [], icon_url: dp(288), position: { x: 4, y: 0 }, levels: lv(5, [66, 66, 66, 66, 66]) },
  { class_id: C.sage, name: 'Abracadabra', slug: 'abracadabra', type: 'active' as const, max_level: 10, target: 'self' as const, description: 'Efeito aleatório poderoso.', prerequisites: [], icon_url: dp(291), position: { x: 4, y: 2 }, levels: lv(10, [50, 50, 50, 50, 50, 50, 50, 50, 50, 50]) },

  // ── High Wizard (6) ──
  { class_id: C.high_wizard, name: 'Mystical Amplification', slug: 'mystical-amplification', type: 'buff' as const, max_level: 10, target: 'self' as const, description: 'Aumenta poder mágico da próxima skill.', prerequisites: [], icon_url: dp(366), position: { x: 0, y: 0 }, levels: lv(10, [14, 14, 14, 14, 14, 14, 14, 14, 14, 14]) },
  { class_id: C.high_wizard, name: 'Napalm Vulcan', slug: 'napalm-vulcan', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Napalm Beat versão transcendente.', prerequisites: [], icon_url: dp(367), position: { x: 1, y: 0 }, levels: lv(5, [40, 45, 50, 55, 60]) },
  { class_id: C.high_wizard, name: 'Gravitation Field', slug: 'gravitation-field', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Campo gravitacional que causa dano.', prerequisites: [], icon_url: dp(368), position: { x: 2, y: 0 }, levels: lv(5, [20, 40, 60, 80, 100]) },
  { class_id: C.high_wizard, name: 'Ganbantein', slug: 'ganbantein', type: 'active' as const, max_level: 1, target: 'area' as const, description: 'Remove todas as magias de área.', prerequisites: [], icon_url: dp(369), position: { x: 3, y: 0 }, levels: lv(1, [40]) },
  { class_id: C.high_wizard, name: 'Stave Crasher', slug: 'stave-crasher', type: 'active' as const, max_level: 1, target: 'enemy' as const, description: 'Ataque com cajado baseado em MATK.', prerequisites: [], icon_url: dp(370), position: { x: 4, y: 0 }, levels: lv(1, [8]) },
  { class_id: C.high_wizard, name: 'Amplify Magic Power', slug: 'amplify-magic-power', type: 'buff' as const, max_level: 10, target: 'self' as const, description: 'Aumenta MATK temporariamente.', prerequisites: [], icon_url: dp(371), position: { x: 0, y: 2 }, levels: lv(10, [10, 14, 18, 22, 26, 30, 34, 38, 42, 46]) },

  // ── Scholar (6) ──
  { class_id: C.scholar, name: 'Double Casting', slug: 'double-casting', type: 'passive' as const, max_level: 5, description: 'Chance de conjurar duas vezes.', prerequisites: [], icon_url: dp(372), position: { x: 0, y: 0 }, levels: lv(5, [0]) },
  { class_id: C.scholar, name: 'Spell Fist', slug: 'spell-fist', type: 'active' as const, max_level: 5, target: 'self' as const, description: 'Infunde magia nos punhos.', prerequisites: [], icon_url: dp(373), position: { x: 1, y: 0 }, levels: lv(5, [40, 44, 48, 52, 56]) },
  { class_id: C.scholar, name: 'Indulge', slug: 'indulge', type: 'active' as const, max_level: 5, target: 'ally' as const, description: 'Transfere SP para um aliado.', prerequisites: [], icon_url: dp(374), position: { x: 2, y: 0 }, levels: lv(5, [10, 10, 10, 10, 10]) },
  { class_id: C.scholar, name: 'Foresight', slug: 'foresight', type: 'buff' as const, max_level: 1, target: 'self' as const, description: 'Dispensa reagentes de magias.', prerequisites: [], icon_url: dp(375), position: { x: 3, y: 0 }, levels: lv(1, [80]) },
  { class_id: C.scholar, name: 'Blinding Mist', slug: 'blinding-mist', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Cria névoa que cega inimigos.', prerequisites: [], icon_url: dp(376), position: { x: 4, y: 0 }, levels: lv(5, [22, 24, 26, 28, 30]) },
  { class_id: C.scholar, name: 'Free Research', slug: 'free-research', type: 'passive' as const, max_level: 5, description: 'Aumenta MAX SP e redução de cast.', prerequisites: [], icon_url: dp(377), position: { x: 0, y: 2 }, levels: lv(5, [0]) },

  // ── Arcane Master (6) ──
  { class_id: C.arcane_master, name: 'Tetra Vortex', slug: 'tetra-vortex', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Ataque dos 4 elementos combinados.', prerequisites: [], icon_url: dp(2208), position: { x: 0, y: 0 }, levels: lv(5, [120, 150, 180, 210, 240]) },
  { class_id: C.arcane_master, name: 'Comet', slug: 'comet', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Invoca um cometa devastador.', prerequisites: [], icon_url: dp(2209), position: { x: 1, y: 0 }, levels: lv(5, [480, 560, 640, 720, 800]) },
  { class_id: C.arcane_master, name: 'Diamondstorm', slug: 'diamondstorm', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Tempestade de cristais de gelo.', prerequisites: [], icon_url: dp(2210), position: { x: 2, y: 0 }, levels: lv(5, [50, 60, 70, 80, 90]) },
  { class_id: C.arcane_master, name: 'Chain Lightning', slug: 'chain-lightning', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Raio que pula entre inimigos.', prerequisites: [], icon_url: dp(2211), position: { x: 3, y: 0 }, levels: lv(5, [80, 90, 100, 110, 120]) },
  { class_id: C.arcane_master, name: 'Crimson Rock', slug: 'crimson-rock', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Meteoro de fogo concentrado.', prerequisites: [], icon_url: dp(2212), position: { x: 4, y: 0 }, levels: lv(5, [60, 70, 80, 90, 100]) },
  { class_id: C.arcane_master, name: 'Jack Frost', slug: 'jack-frost', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Congela toda a área ao redor.', prerequisites: [], icon_url: dp(2213), position: { x: 4, y: 2 }, levels: lv(5, [50, 60, 70, 80, 90]) },

  // ── Sorcerer (6) ──
  { class_id: C.sorcerer, name: 'Psychic Wave', slug: 'psychic-wave', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Onda psíquica em grande área.', prerequisites: [], icon_url: dp(2443), position: { x: 0, y: 0 }, levels: lv(10, [48, 52, 56, 60, 64, 68, 72, 76, 80, 84]) },
  { class_id: C.sorcerer, name: 'Striking', slug: 'striking', type: 'support' as const, max_level: 5, target: 'ally' as const, description: 'Aumenta ATK e chance de crítico de um aliado.', prerequisites: [], icon_url: dp(2444), position: { x: 1, y: 0 }, levels: lv(5, [10, 12, 14, 16, 18]) },
  { class_id: C.sorcerer, name: 'Varetyr Spear', slug: 'varetyr-spear', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Lança elemental de trovão.', prerequisites: [], icon_url: dp(2445), position: { x: 2, y: 0 }, levels: lv(5, [55, 62, 69, 76, 83]) },
  { class_id: C.sorcerer, name: 'Diamond Dust', slug: 'diamond-dust', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Poeira de diamante que congela.', prerequisites: [], icon_url: dp(2446), position: { x: 3, y: 0 }, levels: lv(5, [50, 56, 62, 68, 74]) },
  { class_id: C.sorcerer, name: 'Ball Lightning', slug: 'ball-lightning', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Esfera elétrica em área.', prerequisites: [], icon_url: dp(2447), position: { x: 4, y: 0 }, levels: lv(5, [60, 68, 76, 84, 92]) },
  { class_id: C.sorcerer, name: 'Elemental Control', slug: 'elemental-control', type: 'active' as const, max_level: 4, target: 'self' as const, description: 'Controla elementais invocados.', prerequisites: [], icon_url: dp(2448), position: { x: 4, y: 2 }, levels: lv(4, [40, 50, 60, 70]) },
]
