import { C, S, lv, dp } from './shared'

export const archerChainSkills = [
  // ── Archer (6) ──
  { _id: S.owls_eye, class_id: C.archer, name: "Owl's Eye", slug: 'owls-eye', type: 'passive' as const, max_level: 10, description: 'Aumenta DEX.', prerequisites: [], icon_url: dp(43), position: { x: 0, y: 0 }, levels: lv(10, [0]) },
  { _id: S.vultures_eye, class_id: C.archer, name: "Vulture's Eye", slug: 'vultures-eye', type: 'passive' as const, max_level: 10, description: 'Aumenta alcance e HIT com arco.', prerequisites: [], icon_url: dp(44), position: { x: 2, y: 0 }, levels: lv(10, [0]) },
  { _id: S.improve_concentration, class_id: C.archer, name: 'Improve Concentration', slug: 'improve-concentration', type: 'buff' as const, max_level: 10, target: 'self' as const, description: 'Aumenta AGI e DEX.', prerequisites: [], icon_url: dp(45), position: { x: 4, y: 0 }, levels: lv(10, [15, 18, 21, 24, 27, 30, 33, 36, 39, 42]) },
  { _id: S.double_strafe, class_id: C.archer, name: 'Double Strafe', slug: 'double-strafe', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Dispara duas flechas seguidas.', prerequisites: [], icon_url: dp(46), position: { x: 0, y: 2 }, levels: lv(10, [12, 12, 12, 12, 12, 12, 12, 12, 12, 12]) },
  { _id: S.arrow_shower, class_id: C.archer, name: 'Arrow Shower', slug: 'arrow-shower', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Chuva de flechas em área.', prerequisites: [], icon_url: dp(47), position: { x: 2, y: 2 }, levels: lv(10, [15, 15, 15, 15, 15, 15, 15, 15, 15, 15]) },
  { class_id: C.archer, name: 'Arrow Repel', slug: 'arrow-repel', type: 'active' as const, max_level: 1, target: 'enemy' as const, description: 'Empurra inimigo com flecha.', prerequisites: [], icon_url: dp(48), position: { x: 4, y: 2 }, levels: lv(1, [15]) },

  // ── Hunter (8) ──
  { _id: S.falcon_mastery, class_id: C.hunter, name: 'Falcon Mastery', slug: 'falcon-mastery', type: 'passive' as const, max_level: 1, description: 'Permite ter um falcão.', prerequisites: [], icon_url: dp(127), position: { x: 0, y: 0 }, levels: lv(1, [0]) },
  { class_id: C.hunter, name: 'Blitz Beat', slug: 'blitz-beat', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'O falcão ataca o inimigo.', prerequisites: [{ skill_id: S.falcon_mastery, required_level: 1 }], icon_url: dp(129), position: { x: 0, y: 2 }, levels: lv(5, [10, 10, 10, 10, 10]) },
  { class_id: C.hunter, name: 'True Sight', slug: 'true-sight-hunter', type: 'passive' as const, max_level: 10, description: 'Aumenta todos os status.', prerequisites: [], icon_url: dp(130), position: { x: 1, y: 0 }, levels: lv(10, [0]) },
  { class_id: C.hunter, name: 'Sharp Shooting', slug: 'sharp-shooting', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Tiro preciso com alto dano.', prerequisites: [], icon_url: dp(131), position: { x: 2, y: 0 }, levels: lv(5, [18, 21, 24, 27, 30]) },
  { class_id: C.hunter, name: 'Ankle Snare', slug: 'ankle-snare', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Armadilha que prende inimigos.', prerequisites: [], icon_url: dp(117), position: { x: 3, y: 0 }, levels: lv(5, [12, 12, 12, 12, 12]) },
  { class_id: C.hunter, name: 'Claymore Trap', slug: 'claymore-trap', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Armadilha explosiva de fogo.', prerequisites: [], icon_url: dp(120), position: { x: 4, y: 0 }, levels: lv(5, [15, 15, 15, 15, 15]) },
  { class_id: C.hunter, name: 'Beast Bane', slug: 'beast-bane', type: 'passive' as const, max_level: 10, description: 'Dano extra contra Brute e Insect.', prerequisites: [], icon_url: dp(128), position: { x: 1, y: 2 }, levels: lv(10, [0]) },
  { class_id: C.hunter, name: 'Remove Trap', slug: 'remove-trap', type: 'active' as const, max_level: 1, target: 'area' as const, description: 'Remove armadilha do chão.', prerequisites: [], icon_url: dp(116), position: { x: 3, y: 2 }, levels: lv(1, [5]) },

  // ── Bard (7) ──
  { class_id: C.bard, name: 'Music Lessons', slug: 'music-lessons', type: 'passive' as const, max_level: 10, description: 'Aumenta efeito das canções e ATK com instrumento.', prerequisites: [], icon_url: dp(315), position: { x: 0, y: 0 }, levels: lv(10, [0]) },
  { class_id: C.bard, name: 'Melody Strike', slug: 'melody-strike', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Ataque musical à distância.', prerequisites: [], icon_url: dp(316), position: { x: 0, y: 2 }, levels: lv(10, [8, 8, 8, 8, 8, 8, 8, 8, 8, 8]) },
  { class_id: C.bard, name: 'A Whistle', slug: 'a-whistle', type: 'buff' as const, max_level: 10, target: 'area' as const, description: 'Aumenta FLEE do grupo.', prerequisites: [], icon_url: dp(317), position: { x: 1, y: 0 }, levels: lv(10, [18, 20, 22, 24, 26, 28, 30, 32, 34, 36]) },
  { class_id: C.bard, name: 'Apple of Idun', slug: 'apple-of-idun', type: 'buff' as const, max_level: 10, target: 'area' as const, description: 'Aumenta HP máximo e recuperação.', prerequisites: [], icon_url: dp(318), position: { x: 2, y: 0 }, levels: lv(10, [40, 42, 44, 46, 48, 50, 52, 54, 56, 58]) },
  { class_id: C.bard, name: 'Poem of Bragi', slug: 'poem-of-bragi', type: 'buff' as const, max_level: 10, target: 'area' as const, description: 'Reduz tempo de conjuração do grupo.', prerequisites: [], icon_url: dp(319), position: { x: 3, y: 0 }, levels: lv(10, [40, 42, 44, 46, 48, 50, 52, 54, 56, 58]) },
  { class_id: C.bard, name: "Loki's Veil", slug: 'lokis-veil', type: 'buff' as const, max_level: 10, target: 'area' as const, description: 'Impede uso de skills na área.', prerequisites: [], icon_url: dp(320), position: { x: 4, y: 0 }, levels: lv(10, [10, 12, 14, 16, 18, 20, 22, 24, 26, 28]) },
  { class_id: C.bard, name: 'Dissonance', slug: 'dissonance', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Causa dano sonoro em área.', prerequisites: [], icon_url: dp(321), position: { x: 4, y: 2 }, levels: lv(10, [18, 20, 22, 24, 26, 28, 30, 32, 34, 36]) },

  // ── Dancer (7) ──
  { class_id: C.dancer, name: 'Dance Lessons', slug: 'dance-lessons', type: 'passive' as const, max_level: 10, description: 'Aumenta efeito das danças e ATK com chicote.', prerequisites: [], icon_url: dp(322), position: { x: 0, y: 0 }, levels: lv(10, [0]) },
  { class_id: C.dancer, name: 'Charming Wink', slug: 'charming-wink', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Seduz o inimigo brevemente.', prerequisites: [], icon_url: dp(323), position: { x: 0, y: 2 }, levels: lv(5, [8, 10, 12, 14, 16]) },
  { class_id: C.dancer, name: 'Lady Luck', slug: 'lady-luck', type: 'buff' as const, max_level: 10, target: 'area' as const, description: 'Aumenta taxa de crítico do grupo.', prerequisites: [], icon_url: dp(324), position: { x: 1, y: 0 }, levels: lv(10, [18, 20, 22, 24, 26, 28, 30, 32, 34, 36]) },
  { class_id: C.dancer, name: "Fortune's Kiss", slug: 'fortunes-kiss', type: 'buff' as const, max_level: 10, target: 'area' as const, description: 'Aumenta chance de crítico do grupo.', prerequisites: [], icon_url: dp(325), position: { x: 2, y: 0 }, levels: lv(10, [40, 42, 44, 46, 48, 50, 52, 54, 56, 58]) },
  { class_id: C.dancer, name: 'Slow Grace', slug: 'slow-grace', type: 'buff' as const, max_level: 10, target: 'area' as const, description: 'Reduz velocidade de ataque dos inimigos.', prerequisites: [], icon_url: dp(326), position: { x: 3, y: 0 }, levels: lv(10, [40, 42, 44, 46, 48, 50, 52, 54, 56, 58]) },
  { class_id: C.dancer, name: 'Hip Shaker', slug: 'hip-shaker', type: 'buff' as const, max_level: 10, target: 'area' as const, description: 'Drena SP dos inimigos na área.', prerequisites: [], icon_url: dp(327), position: { x: 4, y: 0 }, levels: lv(10, [10, 12, 14, 16, 18, 20, 22, 24, 26, 28]) },
  { class_id: C.dancer, name: 'Encore', slug: 'encore', type: 'active' as const, max_level: 1, target: 'self' as const, description: 'Repete a última dança com metade do SP.', prerequisites: [], icon_url: dp(328), position: { x: 4, y: 2 }, levels: lv(1, [1]) },

  // ── Sniper (6) ──
  { class_id: C.sniper, name: 'True Sight', slug: 'true-sight', type: 'passive' as const, max_level: 10, description: 'Aumenta todos os atributos.', prerequisites: [], icon_url: dp(380), position: { x: 0, y: 0 }, levels: lv(10, [0]) },
  { class_id: C.sniper, name: 'Wind Walk', slug: 'wind-walk', type: 'buff' as const, max_level: 10, target: 'area' as const, description: 'Aumenta FLEE e velocidade de movimento.', prerequisites: [], icon_url: dp(381), position: { x: 1, y: 0 }, levels: lv(10, [26, 30, 34, 38, 42, 46, 50, 54, 58, 62]) },
  { class_id: C.sniper, name: 'Falcon Eyes', slug: 'falcon-eyes', type: 'passive' as const, max_level: 10, description: 'Aumenta HIT e dano crítico.', prerequisites: [], icon_url: dp(382), position: { x: 2, y: 0 }, levels: lv(10, [0]) },
  { class_id: C.sniper, name: 'Falcon Assault', slug: 'falcon-assault', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Ataque poderoso do falcão.', prerequisites: [], icon_url: dp(383), position: { x: 3, y: 0 }, levels: lv(5, [30, 34, 38, 42, 46]) },
  { class_id: C.sniper, name: 'Arrow Storm', slug: 'arrow-storm-sniper', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Chuva de flechas devastadora.', prerequisites: [], icon_url: dp(384), position: { x: 4, y: 0 }, levels: lv(10, [36, 38, 40, 42, 44, 46, 48, 50, 52, 54]) },
  { class_id: C.sniper, name: 'Phantasmic Arrow', slug: 'phantasmic-arrow', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Flecha fantasma que empurra.', prerequisites: [], icon_url: dp(385), position: { x: 4, y: 2 }, levels: lv(5, [10, 10, 10, 10, 10]) },

  // ── Minstrel (5) ──
  { class_id: C.minstrel, name: 'Metallic Sound', slug: 'metallic-sound', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Som metálico que causa dano e drena SP.', prerequisites: [], icon_url: dp(2412), position: { x: 0, y: 0 }, levels: lv(5, [64, 68, 72, 76, 80]) },
  { class_id: C.minstrel, name: 'Swing Dance', slug: 'swing-dance', type: 'buff' as const, max_level: 5, target: 'area' as const, description: 'Aumenta ASPD do grupo.', prerequisites: [], icon_url: dp(2413), position: { x: 1, y: 0 }, levels: lv(5, [42, 46, 50, 54, 58]) },
  { class_id: C.minstrel, name: 'Serenade of Jordi', slug: 'serenade-of-jordi', type: 'buff' as const, max_level: 5, target: 'area' as const, description: 'Cura HP do grupo com música.', prerequisites: [], icon_url: dp(2414), position: { x: 2, y: 0 }, levels: lv(5, [38, 42, 46, 50, 54]) },
  { class_id: C.minstrel, name: 'March of Prontera', slug: 'march-of-prontera', type: 'buff' as const, max_level: 5, target: 'area' as const, description: 'Aumenta ATK do grupo.', prerequisites: [], icon_url: dp(2415), position: { x: 3, y: 0 }, levels: lv(5, [46, 50, 54, 58, 62]) },
  { class_id: C.minstrel, name: 'Song of Mana', slug: 'song-of-mana', type: 'buff' as const, max_level: 5, target: 'area' as const, description: 'Regenera SP do grupo.', prerequisites: [], icon_url: dp(2416), position: { x: 4, y: 0 }, levels: lv(5, [50, 54, 58, 62, 66]) },

  // ── Wanderer (5) ──
  { class_id: C.wanderer, name: 'Severe Rainstorm', slug: 'severe-rainstorm', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Chuva de flechas massiva em área.', prerequisites: [], icon_url: dp(2418), position: { x: 0, y: 0 }, levels: lv(5, [90, 100, 110, 120, 130]) },
  { class_id: C.wanderer, name: 'Hawkeye', slug: 'hawkeye', type: 'buff' as const, max_level: 5, target: 'self' as const, description: 'Aumenta alcance e precisão.', prerequisites: [], icon_url: dp(2419), position: { x: 1, y: 0 }, levels: lv(5, [20, 24, 28, 32, 36]) },
  { class_id: C.wanderer, name: 'Dance with Wargs', slug: 'dance-with-wargs', type: 'buff' as const, max_level: 5, target: 'area' as const, description: 'Aumenta ATK do grupo com dança.', prerequisites: [], icon_url: dp(2420), position: { x: 2, y: 0 }, levels: lv(5, [40, 44, 48, 52, 56]) },
  { class_id: C.wanderer, name: 'Valley of Death', slug: 'valley-of-death', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Vale da morte que danifica inimigos.', prerequisites: [], icon_url: dp(2421), position: { x: 3, y: 0 }, levels: lv(5, [36, 40, 44, 48, 52]) },
  { class_id: C.wanderer, name: 'Charming Wink Enhanced', slug: 'charming-wink-enhanced', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Versão melhorada de Charming Wink.', prerequisites: [], icon_url: dp(2422), position: { x: 4, y: 0 }, levels: lv(5, [20, 24, 28, 32, 36]) },

  // ── Ranger (6) ──
  { _id: S.warg_mastery, class_id: C.ranger, name: 'Warg Mastery', slug: 'warg-mastery', type: 'passive' as const, max_level: 1, description: 'Permite ter um warg.', prerequisites: [], icon_url: dp(2226), position: { x: 0, y: 0 }, levels: lv(1, [0]) },
  { class_id: C.ranger, name: 'Warg Rider', slug: 'warg-rider', type: 'passive' as const, max_level: 3, description: 'Permite montar no warg.', prerequisites: [], icon_url: dp(2227), position: { x: 0, y: 2 }, levels: lv(3, [0]) },
  { class_id: C.ranger, name: 'Warg Bite', slug: 'warg-bite', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'O warg morde o inimigo.', prerequisites: [{ skill_id: S.warg_mastery, required_level: 1 }], icon_url: dp(2228), position: { x: 1, y: 2 }, levels: lv(5, [12, 14, 16, 18, 20]) },
  { class_id: C.ranger, name: 'Arrow Storm', slug: 'arrow-storm', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Tempestade de flechas avançada.', prerequisites: [], icon_url: dp(2234), position: { x: 2, y: 0 }, levels: lv(10, [30, 34, 38, 42, 46, 50, 54, 58, 62, 66]) },
  { class_id: C.ranger, name: 'Camouflage', slug: 'camouflage', type: 'buff' as const, max_level: 5, target: 'self' as const, description: 'Fica invisível próximo a paredes.', prerequisites: [], icon_url: dp(2235), position: { x: 3, y: 0 }, levels: lv(5, [40, 40, 40, 40, 40]) },
  { class_id: C.ranger, name: 'Aimed Bolt', slug: 'aimed-bolt', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Tiro certeiro com dano extra em presos.', prerequisites: [], icon_url: dp(2236), position: { x: 4, y: 0 }, levels: lv(10, [20, 24, 28, 32, 36, 40, 44, 48, 52, 56]) },

  // ── Maestro (5) ──
  { class_id: C.maestro, name: 'Metallic Sound Enhanced', slug: 'metallic-sound-enhanced', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Versão melhorada de Metallic Sound.', prerequisites: [], icon_url: dp(2560), position: { x: 0, y: 0 }, levels: lv(5, [70, 76, 82, 88, 94]) },
  { class_id: C.maestro, name: 'Swing Dance Enhanced', slug: 'swing-dance-enhanced', type: 'buff' as const, max_level: 5, target: 'area' as const, description: 'Swing Dance com efeito amplificado.', prerequisites: [], icon_url: dp(2561), position: { x: 1, y: 0 }, levels: lv(5, [48, 52, 56, 60, 64]) },
  { class_id: C.maestro, name: 'Serenade of Jordi Enhanced', slug: 'serenade-of-jordi-enhanced', type: 'buff' as const, max_level: 5, target: 'area' as const, description: 'Serenade of Jordi com cura amplificada.', prerequisites: [], icon_url: dp(2562), position: { x: 2, y: 0 }, levels: lv(5, [44, 48, 52, 56, 60]) },
  { class_id: C.maestro, name: 'March of Prontera Enhanced', slug: 'march-of-prontera-enhanced', type: 'buff' as const, max_level: 5, target: 'area' as const, description: 'March of Prontera com bônus maior.', prerequisites: [], icon_url: dp(2563), position: { x: 3, y: 0 }, levels: lv(5, [52, 56, 60, 64, 68]) },
  { class_id: C.maestro, name: 'Song of Mana Enhanced', slug: 'song-of-mana-enhanced', type: 'buff' as const, max_level: 5, target: 'area' as const, description: 'Song of Mana com regeneração maior.', prerequisites: [], icon_url: dp(2564), position: { x: 4, y: 0 }, levels: lv(5, [56, 60, 64, 68, 72]) },
]
