import { C, S, lv, dp } from './shared'

export const thiefChainSkills = [
  // ── Thief (8) ──
  { _id: S.double_attack, class_id: C.thief, name: 'Double Attack', slug: 'double-attack', type: 'passive' as const, max_level: 10, description: 'Chance de ataque duplo com adagas.', prerequisites: [], icon_url: dp(48), position: { x: 0, y: 0 }, levels: lv(10, [0]) },
  { _id: S.steal, class_id: C.thief, name: 'Steal', slug: 'steal', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Rouba itens do monstro.', prerequisites: [], icon_url: dp(49), position: { x: 2, y: 0 }, levels: lv(10, [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]) },
  { _id: S.hiding, class_id: C.thief, name: 'Hiding', slug: 'hiding', type: 'buff' as const, max_level: 10, target: 'self' as const, description: 'Esconde-se dos inimigos.', prerequisites: [], icon_url: dp(51), position: { x: 4, y: 0 }, levels: lv(10, [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]) },
  { class_id: C.thief, name: 'Cloaking', slug: 'cloaking', type: 'buff' as const, max_level: 10, target: 'self' as const, description: 'Invisibilidade ao se mover perto de paredes.', prerequisites: [], icon_url: dp(135), position: { x: 4, y: 2 }, levels: lv(10, [15, 15, 15, 15, 15, 15, 15, 15, 15, 15]) },
  { class_id: C.thief, name: 'Detoxify', slug: 'detoxify', type: 'active' as const, max_level: 5, target: 'ally' as const, description: 'Remove envenenamento.', prerequisites: [], icon_url: dp(54), position: { x: 1, y: 0 }, levels: lv(5, [10, 10, 10, 10, 10]) },
  { _id: S.envenom, class_id: C.thief, name: 'Envenom', slug: 'envenom', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Envenena o inimigo.', prerequisites: [], icon_url: dp(52), position: { x: 1, y: 2 }, levels: lv(10, [12, 12, 12, 12, 12, 12, 12, 12, 12, 12]) },
  { class_id: C.thief, name: 'Improve Dodge', slug: 'improve-dodge', type: 'passive' as const, max_level: 10, description: 'Aumenta FLEE.', prerequisites: [], icon_url: dp(50), position: { x: 3, y: 0 }, levels: lv(10, [0]) },
  { class_id: C.thief, name: 'Pickpocket', slug: 'pickpocket', type: 'passive' as const, max_level: 10, description: 'Chance de roubar ao atacar.', prerequisites: [], icon_url: dp(53), position: { x: 3, y: 2 }, levels: lv(10, [0]) },

  // ── Assassin (8) ──
  { _id: S.katar_mastery, class_id: C.assassin, name: 'Katar Mastery', slug: 'katar-mastery', type: 'passive' as const, max_level: 10, description: 'Aumenta ATK com katars.', prerequisites: [], icon_url: dp(134), position: { x: 0, y: 0 }, levels: lv(10, [0]) },
  { class_id: C.assassin, name: 'Grimtooth', slug: 'grimtooth', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Ataque à distância enquanto escondido.', prerequisites: [], icon_url: dp(137), position: { x: 0, y: 2 }, levels: lv(5, [3, 3, 3, 3, 3]) },
  { class_id: C.assassin, name: 'Enchant Poison', slug: 'enchant-poison', type: 'buff' as const, max_level: 10, target: 'self' as const, description: 'Encanta arma com propriedade veneno.', prerequisites: [], icon_url: dp(136), position: { x: 1, y: 0 }, levels: lv(10, [20, 20, 20, 20, 20, 20, 20, 20, 20, 20]) },
  { class_id: C.assassin, name: 'Poison React', slug: 'poison-react', type: 'buff' as const, max_level: 10, target: 'self' as const, description: 'Contra-ataca com veneno.', prerequisites: [], icon_url: dp(138), position: { x: 2, y: 0 }, levels: lv(10, [25, 25, 25, 25, 25, 25, 25, 25, 25, 25]) },
  { class_id: C.assassin, name: 'Venom Dust', slug: 'venom-dust', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Cria nuvem venenosa no chão.', prerequisites: [], icon_url: dp(139), position: { x: 3, y: 0 }, levels: lv(10, [20, 20, 20, 20, 20, 20, 20, 20, 20, 20]) },
  { class_id: C.assassin, name: 'Venom Splasher', slug: 'venom-splasher', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Bomba venenosa no alvo.', prerequisites: [], icon_url: dp(140), position: { x: 4, y: 0 }, levels: lv(10, [12, 14, 16, 18, 20, 22, 24, 26, 28, 30]) },
  { class_id: C.assassin, name: 'Meteor Assault', slug: 'meteor-assault', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Ataque em área ao redor.', prerequisites: [], icon_url: dp(406), position: { x: 3, y: 2 }, levels: lv(10, [10, 12, 14, 16, 18, 20, 22, 24, 26, 28]) },
  { _id: S.sonic_blow, class_id: C.assassin, name: 'Sonic Blow', slug: 'sonic-blow', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: '8 golpes rápidos no inimigo.', prerequisites: [{ skill_id: S.katar_mastery, required_level: 5 }], icon_url: dp(136), position: { x: 0, y: 4 }, levels: lv(10, [16, 18, 20, 22, 24, 26, 28, 30, 32, 34]) },

  // ── Assassin Cross (6) ──
  { class_id: C.assassin_cross, name: 'Enchant Deadly Poison', slug: 'enchant-deadly-poison', type: 'buff' as const, max_level: 5, target: 'self' as const, description: 'Encanta arma com veneno letal.', prerequisites: [], icon_url: dp(378), position: { x: 0, y: 0 }, levels: lv(5, [60, 70, 80, 90, 100]) },
  { class_id: C.assassin_cross, name: 'Soul Destroyer', slug: 'soul-destroyer', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Ataque à distância com ATK + MATK.', prerequisites: [], icon_url: dp(379), position: { x: 1, y: 0 }, levels: lv(10, [20, 22, 24, 26, 28, 30, 32, 34, 36, 38]) },
  { class_id: C.assassin_cross, name: 'Right-Hand Mastery', slug: 'right-hand-mastery', type: 'passive' as const, max_level: 5, description: 'Aumenta ATK da mão direita em dual wield.', prerequisites: [], icon_url: dp(133), position: { x: 2, y: 0 }, levels: lv(5, [0]) },
  { class_id: C.assassin_cross, name: 'Left-Hand Mastery', slug: 'left-hand-mastery', type: 'passive' as const, max_level: 5, description: 'Aumenta ATK da mão esquerda em dual wield.', prerequisites: [], icon_url: dp(132), position: { x: 3, y: 0 }, levels: lv(5, [0]) },
  { class_id: C.assassin_cross, name: 'Venom Knife', slug: 'venom-knife', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Arremessa adaga envenenada.', prerequisites: [], icon_url: dp(413), position: { x: 4, y: 0 }, levels: lv(5, [15, 15, 15, 15, 15]) },
  { class_id: C.assassin_cross, name: 'Sonic Acceleration', slug: 'sonic-acceleration', type: 'passive' as const, max_level: 5, description: 'Aumenta dano e HIT de Sonic Blow.', prerequisites: [], icon_url: dp(414), position: { x: 0, y: 2 }, levels: lv(5, [0]) },

  // ── Guillotine Cross (6) ──
  { class_id: C.guillotine_cross, name: 'Cross Impact', slug: 'cross-impact', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: '7 golpes rápidos que ignoram FLEE.', prerequisites: [], icon_url: dp(2073), position: { x: 0, y: 0 }, levels: lv(10, [25, 28, 31, 34, 37, 40, 43, 46, 49, 52]) },
  { class_id: C.guillotine_cross, name: 'Counter Slash', slug: 'counter-slash', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Contra-ataque em área.', prerequisites: [], icon_url: dp(2074), position: { x: 1, y: 0 }, levels: lv(5, [5, 5, 5, 5, 5]) },
  { class_id: C.guillotine_cross, name: 'Dark Illusion', slug: 'dark-illusion', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Teleporte para o alvo com ataque.', prerequisites: [], icon_url: dp(2075), position: { x: 2, y: 0 }, levels: lv(5, [30, 30, 30, 30, 30]) },
  { class_id: C.guillotine_cross, name: 'Phantom Menace', slug: 'phantom-menace', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Revela e dano em inimigos escondidos.', prerequisites: [], icon_url: dp(2076), position: { x: 3, y: 0 }, levels: lv(5, [12, 14, 16, 18, 20]) },
  { class_id: C.guillotine_cross, name: 'Hallucination Walk', slug: 'hallucination-walk', type: 'buff' as const, max_level: 5, target: 'self' as const, description: 'Aumenta FLEE massivamente.', prerequisites: [], icon_url: dp(2077), position: { x: 4, y: 0 }, levels: lv(5, [100, 100, 100, 100, 100]) },
  { class_id: C.guillotine_cross, name: 'Crazy Uproar', slug: 'crazy-uproar', type: 'buff' as const, max_level: 1, target: 'self' as const, description: 'Aumenta STR.', prerequisites: [], icon_url: dp(2078), position: { x: 4, y: 2 }, levels: lv(1, [15]) },

  // ── Rogue (7) ──
  { class_id: C.rogue, name: 'Steal Coin', slug: 'steal-coin', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Rouba zeny do inimigo.', prerequisites: [], icon_url: dp(210), position: { x: 0, y: 0 }, levels: lv(10, [15, 15, 15, 15, 15, 15, 15, 15, 15, 15]) },
  { class_id: C.rogue, name: 'Backstab', slug: 'backstab', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Ataque pelas costas.', prerequisites: [], icon_url: dp(211), position: { x: 1, y: 0 }, levels: lv(10, [16, 16, 16, 16, 16, 16, 16, 16, 16, 16]) },
  { class_id: C.rogue, name: 'Raid', slug: 'raid', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Ataque em área que cega e atordoa.', prerequisites: [], icon_url: dp(214), position: { x: 2, y: 0 }, levels: lv(5, [20, 20, 20, 20, 20]) },
  { class_id: C.rogue, name: 'Intimidate', slug: 'intimidate', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Ataque que teleporta ambos.', prerequisites: [], icon_url: dp(215), position: { x: 3, y: 0 }, levels: lv(10, [13, 14, 15, 16, 17, 18, 19, 20, 21, 22]) },
  { class_id: C.rogue, name: 'Snatcher', slug: 'snatcher', type: 'passive' as const, max_level: 10, description: 'Auto-roubo ao atacar.', prerequisites: [], icon_url: dp(216), position: { x: 4, y: 0 }, levels: lv(10, [0]) },
  { class_id: C.rogue, name: 'Gangster Paradise', slug: 'gangster-paradise', type: 'passive' as const, max_level: 1, description: 'Imunidade a ataques quando sentado em grupo.', prerequisites: [], icon_url: dp(212), position: { x: 4, y: 2 }, levels: lv(1, [0]) },
  { class_id: C.rogue, name: 'Sword Mastery Rogue', slug: 'sword-mastery-rogue', type: 'passive' as const, max_level: 10, description: 'Aumenta ATK com espadas.', prerequisites: [], icon_url: dp(2), position: { x: 0, y: 2 }, levels: lv(10, [0]) },

  // ── Stalker (6) ──
  { class_id: C.stalker, name: 'Full Strip', slug: 'full-strip', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Remove todo equipamento do alvo.', prerequisites: [], icon_url: dp(217), position: { x: 0, y: 0 }, levels: lv(5, [17, 19, 21, 23, 25]) },
  { class_id: C.stalker, name: 'Chase Walk', slug: 'chase-walk', type: 'buff' as const, max_level: 5, target: 'self' as const, description: 'Invisibilidade avançada que aumenta STR.', prerequisites: [], icon_url: dp(388), position: { x: 1, y: 0 }, levels: lv(5, [10, 10, 10, 10, 10]) },
  { class_id: C.stalker, name: 'Plagiarism', slug: 'plagiarism', type: 'passive' as const, max_level: 10, description: 'Copia a última skill usada contra você.', prerequisites: [], icon_url: dp(218), position: { x: 2, y: 0 }, levels: lv(10, [0]) },
  { class_id: C.stalker, name: 'Preserve', slug: 'preserve', type: 'active' as const, max_level: 1, target: 'self' as const, description: 'Mantém a skill copiada.', prerequisites: [], icon_url: dp(389), position: { x: 3, y: 0 }, levels: lv(1, [30]) },
  { class_id: C.stalker, name: 'Raid Enhanced', slug: 'raid-enhanced', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Raid versão melhorada.', prerequisites: [], icon_url: dp(390), position: { x: 4, y: 0 }, levels: lv(10, [20, 22, 24, 26, 28, 30, 32, 34, 36, 38]) },
  { class_id: C.stalker, name: 'Tunnel Drive', slug: 'tunnel-drive', type: 'passive' as const, max_level: 5, description: 'Permite mover enquanto escondido.', prerequisites: [], icon_url: dp(213), position: { x: 0, y: 2 }, levels: lv(5, [0]) },

  // ── Shadow Chaser (6) ──
  { class_id: C.shadow_chaser, name: 'Chaos Panic', slug: 'chaos-panic', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Confusão em área.', prerequisites: [], icon_url: dp(2323), position: { x: 0, y: 0 }, levels: lv(5, [30, 34, 38, 42, 46]) },
  { class_id: C.shadow_chaser, name: 'Masquerade Piercing', slug: 'masquerade-piercing', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Causa sangramento e remove montaria.', prerequisites: [], icon_url: dp(2324), position: { x: 1, y: 0 }, levels: lv(5, [20, 24, 28, 32, 36]) },
  { class_id: C.shadow_chaser, name: 'Masquerade Enervation', slug: 'masquerade-enervation', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Reduz ATK do alvo.', prerequisites: [], icon_url: dp(2325), position: { x: 2, y: 0 }, levels: lv(5, [20, 24, 28, 32, 36]) },
  { class_id: C.shadow_chaser, name: 'Masquerade Ignorance', slug: 'masquerade-ignorance', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Drena SP e impede uso de skills.', prerequisites: [], icon_url: dp(2326), position: { x: 3, y: 0 }, levels: lv(5, [20, 24, 28, 32, 36]) },
  { class_id: C.shadow_chaser, name: 'Masquerade Stupidity', slug: 'masquerade-stupidity', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Reduz INT e impede magias.', prerequisites: [], icon_url: dp(2327), position: { x: 4, y: 0 }, levels: lv(5, [20, 24, 28, 32, 36]) },
  { class_id: C.shadow_chaser, name: 'Shadow Form', slug: 'shadow-form', type: 'buff' as const, max_level: 5, target: 'self' as const, description: 'Transfere dano recebido para outro alvo.', prerequisites: [], icon_url: dp(2328), position: { x: 0, y: 2 }, levels: lv(5, [40, 40, 40, 40, 40]) },
]
