import { C, S, lv } from './shared'

export const thiefChainSkills = [
  // ── Thief (8) ──
  { _id: S.double_attack, class_id: C.thief, name: 'Ataque Duplo', slug: 'double-attack', type: 'passive' as const, max_level: 10, description: 'Chance de ataque duplo com adagas.', prerequisites: [], icon_url: 'https://browiki.org/images/1/12/Ataque_Duplo.png', position: { x: 0, y: 0 }, levels: lv(10, [0]) },
  { _id: S.steal, class_id: C.thief, name: 'Furto', slug: 'steal', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Rouba itens do monstro.', prerequisites: [], icon_url: 'https://browiki.org/images/a/a9/Furto.png', position: { x: 2, y: 0 }, levels: lv(10, [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]) },
  { _id: S.hiding, class_id: C.thief, name: 'Esconderijo', slug: 'hiding', type: 'buff' as const, max_level: 10, target: 'self' as const, description: 'Esconde-se dos inimigos.', prerequisites: [], icon_url: 'https://browiki.org/images/9/94/Esconderijo.png', position: { x: 4, y: 0 }, levels: lv(10, [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]) },
  { class_id: C.thief, name: 'Furtividade', slug: 'cloaking', type: 'buff' as const, max_level: 10, target: 'self' as const, description: 'Invisibilidade ao se mover perto de paredes.', prerequisites: [], icon_url: 'https://browiki.org/images/6/6e/Furtividade.png', position: { x: 4, y: 2 }, levels: lv(10, [15, 15, 15, 15, 15, 15, 15, 15, 15, 15]) },
  { class_id: C.thief, name: 'Desintoxicar', slug: 'detoxify', type: 'active' as const, max_level: 5, target: 'ally' as const, description: 'Remove envenenamento.', prerequisites: [], icon_url: 'https://browiki.org/images/2/2e/Desintoxicar.png', position: { x: 1, y: 0 }, levels: lv(5, [10, 10, 10, 10, 10]) },
  { _id: S.envenom, class_id: C.thief, name: 'Envenenar', slug: 'envenom', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Envenena o inimigo.', prerequisites: [], icon_url: 'https://browiki.org/images/f/f6/Envenenar.png', position: { x: 1, y: 2 }, levels: lv(10, [12, 12, 12, 12, 12, 12, 12, 12, 12, 12]) },
  { class_id: C.thief, name: 'Perícia em Esquiva', slug: 'improve-dodge', type: 'passive' as const, max_level: 10, description: 'Aumenta FLEE.', prerequisites: [], icon_url: 'https://browiki.org/images/5/57/Per%C3%ADcia_em_Esquiva.png', position: { x: 3, y: 0 }, levels: lv(10, [0]) },
  { class_id: C.thief, name: 'Afanar', slug: 'pickpocket', type: 'passive' as const, max_level: 10, description: 'Chance de roubar ao atacar.', prerequisites: [], icon_url: 'https://browiki.org/images/f/f3/Afanar.png', position: { x: 3, y: 2 }, levels: lv(10, [0]) },

  // ── Assassin (8) ──
  { _id: S.katar_mastery, class_id: C.assassin, name: 'Perícia com Katar', slug: 'katar-mastery', type: 'passive' as const, max_level: 10, description: 'Aumenta ATK com katars.', prerequisites: [], icon_url: 'https://browiki.org/images/2/2c/Per%C3%ADcia_com_Katar.png', position: { x: 0, y: 0 }, levels: lv(10, [0]) },
  { class_id: C.assassin, name: 'Tocaia', slug: 'grimtooth', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Ataque à distância enquanto escondido.', prerequisites: [], icon_url: 'https://browiki.org/images/a/a5/Tocaia.png', position: { x: 0, y: 2 }, levels: lv(5, [3, 3, 3, 3, 3]) },
  { class_id: C.assassin, name: 'Envenenar Arma', slug: 'enchant-poison', type: 'buff' as const, max_level: 10, target: 'self' as const, description: 'Encanta arma com propriedade veneno.', prerequisites: [], icon_url: 'https://browiki.org/images/4/40/Envenenar_Arma.png', position: { x: 1, y: 0 }, levels: lv(10, [20, 20, 20, 20, 20, 20, 20, 20, 20, 20]) },
  { class_id: C.assassin, name: 'Refletir Veneno', slug: 'poison-react', type: 'buff' as const, max_level: 10, target: 'self' as const, description: 'Contra-ataca com veneno.', prerequisites: [], icon_url: 'https://browiki.org/images/b/bb/Refletir_Veneno.png', position: { x: 2, y: 0 }, levels: lv(10, [25, 25, 25, 25, 25, 25, 25, 25, 25, 25]) },
  { class_id: C.assassin, name: 'Névoa Tóxica', slug: 'venom-dust', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Cria nuvem venenosa no chão.', prerequisites: [], icon_url: 'https://browiki.org/images/4/4e/N%C3%A9voa_T%C3%B3xica.png', position: { x: 3, y: 0 }, levels: lv(10, [20, 20, 20, 20, 20, 20, 20, 20, 20, 20]) },
  { class_id: C.assassin, name: 'Explosão Tóxica', slug: 'venom-splasher', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Bomba venenosa no alvo.', prerequisites: [], icon_url: 'https://browiki.org/images/8/82/Explos%C3%A3o_T%C3%B3xica.png', position: { x: 4, y: 0 }, levels: lv(10, [12, 14, 16, 18, 20, 22, 24, 26, 28, 30]) },
  { class_id: C.assassin, name: 'Impacto Meteoro', slug: 'meteor-assault', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Ataque em área ao redor.', prerequisites: [], icon_url: 'https://browiki.org/images/6/68/Impacto_Meteoro.png', position: { x: 3, y: 2 }, levels: lv(10, [10, 12, 14, 16, 18, 20, 22, 24, 26, 28]) },
  { _id: S.sonic_blow, class_id: C.assassin, name: 'Lâminas Destruidoras', slug: 'sonic-blow', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: '8 golpes rápidos no inimigo.', prerequisites: [{ skill_id: S.katar_mastery, required_level: 5 }], icon_url: 'https://browiki.org/images/b/bf/L%C3%A2minas_Destruidoras.png', position: { x: 0, y: 4 }, levels: lv(10, [16, 18, 20, 22, 24, 26, 28, 30, 32, 34]) },

  // ── Assassin Cross (6) ──
  { class_id: C.assassin_cross, name: 'Encantar com Veneno Mortal', slug: 'enchant-deadly-poison', type: 'buff' as const, max_level: 5, target: 'self' as const, description: 'Encanta arma com veneno letal.', prerequisites: [], icon_url: 'https://browiki.org/images/f/fc/Encantar_com_Veneno_Mortal.png', position: { x: 0, y: 0 }, levels: lv(5, [60, 70, 80, 90, 100]) },
  { class_id: C.assassin_cross, name: 'Lâminas de Loki', slug: 'soul-destroyer', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Ataque à distância com ATK + MATK.', prerequisites: [], icon_url: 'https://browiki.org/images/1/12/L%C3%A2minas_de_Loki.png', position: { x: 1, y: 0 }, levels: lv(10, [20, 22, 24, 26, 28, 30, 32, 34, 36, 38]) },
  { class_id: C.assassin_cross, name: 'Perícia com Mão Direita', slug: 'right-hand-mastery', type: 'passive' as const, max_level: 5, description: 'Aumenta ATK da mão direita em dual wield.', prerequisites: [], icon_url: 'https://browiki.org/images/6/6c/Per%C3%ADcia_com_M%C3%A3o_Direita.png', position: { x: 2, y: 0 }, levels: lv(5, [0]) },
  { class_id: C.assassin_cross, name: 'Perícia com Mão Esquerda', slug: 'left-hand-mastery', type: 'passive' as const, max_level: 5, description: 'Aumenta ATK da mão esquerda em dual wield.', prerequisites: [], icon_url: 'https://browiki.org/images/a/a5/Per%C3%ADcia_com_M%C3%A3o_Esquerda.png', position: { x: 3, y: 0 }, levels: lv(5, [0]) },
  { class_id: C.assassin_cross, name: 'Faca Envenenada', slug: 'venom-knife', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Arremessa adaga envenenada.', prerequisites: [], icon_url: 'https://browiki.org/images/0/05/Faca_Envenenada.png', position: { x: 4, y: 0 }, levels: lv(5, [15, 15, 15, 15, 15]) },
  { class_id: C.assassin_cross, name: 'Lâminas Aceleradas', slug: 'sonic-acceleration', type: 'passive' as const, max_level: 5, description: 'Aumenta dano e HIT de Sonic Blow.', prerequisites: [], icon_url: 'https://browiki.org/images/0/08/L%C3%A2minas_Aceleradas.png', position: { x: 0, y: 2 }, levels: lv(5, [0]) },

  // ── Guillotine Cross (6) ──
  { class_id: C.guillotine_cross, name: 'Castigo de Loki', slug: 'cross-impact', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: '7 golpes rápidos que ignoram FLEE.', prerequisites: [], icon_url: 'https://browiki.org/images/3/3b/Castigo_de_Loki.png', position: { x: 0, y: 0 }, levels: lv(10, [25, 28, 31, 34, 37, 40, 43, 46, 49, 52]) },
  { class_id: C.guillotine_cross, name: 'Retaliação', slug: 'counter-slash', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Contra-ataque em área.', prerequisites: [], icon_url: 'https://browiki.org/images/b/b3/Retalia%C3%A7%C3%A3o.png', position: { x: 1, y: 0 }, levels: lv(5, [5, 5, 5, 5, 5]) },
  { class_id: C.guillotine_cross, name: 'Passo Sombrio', slug: 'dark-illusion', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Teleporte para o alvo com ataque.', prerequisites: [], icon_url: 'https://browiki.org/images/4/4f/Passo_Sombrio.png', position: { x: 2, y: 0 }, levels: lv(5, [30, 30, 30, 30, 30]) },
  { class_id: C.guillotine_cross, name: 'Ameaça Fantasma', slug: 'phantom-menace', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Revela e dano em inimigos escondidos.', prerequisites: [], icon_url: 'https://browiki.org/images/7/7f/Amea%C3%A7a_Fantasma.png', position: { x: 3, y: 0 }, levels: lv(5, [12, 14, 16, 18, 20]) },
  { class_id: C.guillotine_cross, name: 'Ocultação', slug: 'hallucination-walk', type: 'buff' as const, max_level: 5, target: 'self' as const, description: 'Aumenta FLEE massivamente.', prerequisites: [], icon_url: 'https://browiki.org/images/5/50/Oculta%C3%A7%C3%A3o.png', position: { x: 4, y: 0 }, levels: lv(5, [100, 100, 100, 100, 100]) },
  { class_id: C.guillotine_cross, name: 'Nevoeiro Tóxico', slug: 'crazy-uproar', type: 'buff' as const, max_level: 1, target: 'self' as const, description: 'Aumenta STR.', prerequisites: [], icon_url: 'https://browiki.org/images/f/f4/Nevoeiro_T%C3%B3xico.png', position: { x: 4, y: 2 }, levels: lv(1, [15]) },

  // ── Rogue (7) ──
  { class_id: C.rogue, name: 'Afanar', slug: 'steal-coin', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Rouba zeny do inimigo.', prerequisites: [], icon_url: 'https://browiki.org/images/f/f3/Afanar.png', position: { x: 0, y: 0 }, levels: lv(10, [15, 15, 15, 15, 15, 15, 15, 15, 15, 15]) },
  { class_id: C.rogue, name: 'Apunhalar', slug: 'backstab', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Ataque pelas costas.', prerequisites: [], icon_url: 'https://browiki.org/images/d/d9/Apunhalar.png', position: { x: 1, y: 0 }, levels: lv(10, [16, 16, 16, 16, 16, 16, 16, 16, 16, 16]) },
  { class_id: C.rogue, name: 'Ataque Surpresa', slug: 'raid', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Ataque em área que cega e atordoa.', prerequisites: [], icon_url: 'https://browiki.org/images/0/01/Ataque_Surpresa.png', position: { x: 2, y: 0 }, levels: lv(5, [20, 20, 20, 20, 20]) },
  { class_id: C.rogue, name: 'Rapto', slug: 'intimidate', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Ataque que teleporta ambos.', prerequisites: [], icon_url: 'https://browiki.org/images/d/d8/Rapto.png', position: { x: 3, y: 0 }, levels: lv(10, [13, 14, 15, 16, 17, 18, 19, 20, 21, 22]) },
  { class_id: C.rogue, name: 'Faxina', slug: 'snatcher', type: 'passive' as const, max_level: 10, description: 'Auto-roubo ao atacar.', prerequisites: [], icon_url: 'https://browiki.org/images/5/59/Faxina.png', position: { x: 4, y: 0 }, levels: lv(10, [0]) },
  { class_id: C.rogue, name: 'Pichar', slug: 'gangster-paradise', type: 'passive' as const, max_level: 1, description: 'Imunidade a ataques quando sentado em grupo.', prerequisites: [], icon_url: 'https://browiki.org/images/7/75/Pichar.png', position: { x: 4, y: 2 }, levels: lv(1, [0]) },
  { class_id: C.rogue, name: 'Perícia com Espada', slug: 'sword-mastery-rogue', type: 'passive' as const, max_level: 10, description: 'Aumenta ATK com espadas.', prerequisites: [], icon_url: 'https://browiki.org/images/0/0b/Per%C3%ADcia_com_Espada.png', position: { x: 0, y: 2 }, levels: lv(10, [0]) },

  // ── Stalker (6) ──
  { class_id: C.stalker, name: 'Remoção Total', slug: 'full-strip', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Remove todo equipamento do alvo.', prerequisites: [], icon_url: 'https://browiki.org/images/2/2d/Remo%C3%A7%C3%A3o_Total.png', position: { x: 0, y: 0 }, levels: lv(5, [17, 19, 21, 23, 25]) },
  { class_id: C.stalker, name: 'Espreitar', slug: 'chase-walk', type: 'buff' as const, max_level: 5, target: 'self' as const, description: 'Invisibilidade avançada que aumenta STR.', prerequisites: [], icon_url: 'https://browiki.org/images/7/71/Espreitar.png', position: { x: 1, y: 0 }, levels: lv(5, [10, 10, 10, 10, 10]) },
  { class_id: C.stalker, name: 'Plágio', slug: 'plagiarism', type: 'passive' as const, max_level: 10, description: 'Copia a última skill usada contra você.', prerequisites: [], icon_url: 'https://browiki.org/images/2/28/Pl%C3%A1gio.png', position: { x: 2, y: 0 }, levels: lv(10, [0]) },
  { class_id: C.stalker, name: 'Preservar', slug: 'preserve', type: 'active' as const, max_level: 1, target: 'self' as const, description: 'Mantém a skill copiada.', prerequisites: [], icon_url: 'https://browiki.org/images/4/46/Preservar.png', position: { x: 3, y: 0 }, levels: lv(1, [30]) },
  { class_id: C.stalker, name: 'Confinamento', slug: 'raid-enhanced', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Raid versão melhorada.', prerequisites: [], icon_url: 'https://browiki.org/images/a/af/Confinamento.png', position: { x: 4, y: 0 }, levels: lv(10, [20, 22, 24, 26, 28, 30, 32, 34, 36, 38]) },
  { class_id: C.stalker, name: 'Túnel de Fuga', slug: 'tunnel-drive', type: 'passive' as const, max_level: 5, description: 'Permite mover enquanto escondido.', prerequisites: [], icon_url: 'https://browiki.org/images/1/11/T%C3%BAnel_de_Fuga.png', position: { x: 0, y: 2 }, levels: lv(5, [0]) },

  // ── Shadow Chaser (6) ──
  { class_id: C.shadow_chaser, name: 'Ofensiva Fatal', slug: 'chaos-panic', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Confusão em área.', prerequisites: [], icon_url: 'https://browiki.org/images/9/90/Ofensiva_Fatal.png', position: { x: 0, y: 0 }, levels: lv(5, [30, 34, 38, 42, 46]) },
  { class_id: C.shadow_chaser, name: 'Desejo das Sombras', slug: 'masquerade-piercing', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Causa sangramento e remove montaria.', prerequisites: [], icon_url: 'https://browiki.org/images/6/6b/Desejo_das_Sombras.png', position: { x: 1, y: 0 }, levels: lv(5, [20, 24, 28, 32, 36]) },
  { class_id: C.shadow_chaser, name: 'Escapar', slug: 'masquerade-enervation', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Reduz ATK do alvo.', prerequisites: [], icon_url: 'https://browiki.org/images/3/32/Escapar.png', position: { x: 2, y: 0 }, levels: lv(5, [20, 24, 28, 32, 36]) },
  { class_id: C.shadow_chaser, name: 'Disparo Triplo', slug: 'masquerade-ignorance', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Drena SP e impede uso de skills.', prerequisites: [], icon_url: 'https://browiki.org/images/2/24/Disparo_Triplo.png', position: { x: 3, y: 0 }, levels: lv(5, [20, 24, 28, 32, 36]) },
  { class_id: C.shadow_chaser, name: 'Desejo das Sombras', slug: 'masquerade-stupidity', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Reduz INT e impede magias.', prerequisites: [], icon_url: 'https://browiki.org/images/6/6b/Desejo_das_Sombras.png', position: { x: 4, y: 0 }, levels: lv(5, [20, 24, 28, 32, 36]) },
  { class_id: C.shadow_chaser, name: 'Desejo das Sombras', slug: 'shadow-form', type: 'buff' as const, max_level: 5, target: 'self' as const, description: 'Transfere dano recebido para outro alvo.', prerequisites: [], icon_url: 'https://browiki.org/images/6/6b/Desejo_das_Sombras.png', position: { x: 0, y: 2 }, levels: lv(5, [40, 40, 40, 40, 40]) },
]
