import { C, S, lv, dp } from './shared'

export const swordsmanChainSkills = [
  // ── Swordsman (7) ──
  { _id: S.sword_mastery, class_id: C.swordsman, name: 'Perícia com Espada', slug: 'sword-mastery', type: 'passive' as const, max_level: 10, description: 'Aumenta ATK com espadas.', prerequisites: [], icon_url: 'https://browiki.org/images/0/0b/Per%C3%ADcia_com_Espada.png', position: { x: 0, y: 0 }, levels: lv(10, [0]) },
  { _id: S.twohand_mastery, class_id: C.swordsman, name: 'Perícia com Espada de Duas Mãos', slug: 'twohand-sword-mastery', type: 'passive' as const, max_level: 10, description: 'Aumenta ATK com espadas de duas mãos.', prerequisites: [], icon_url: 'https://browiki.org/images/4/47/Per%C3%ADcia_com_Espada_de_Duas_M%C3%A3os.png', position: { x: 2, y: 0 }, levels: lv(10, [0]) },
  { _id: S.hp_recovery, class_id: C.swordsman, name: 'Aumentar Recuperação de HP', slug: 'increase-hp-recovery', type: 'passive' as const, max_level: 10, description: 'Aumenta recuperação natural de HP.', prerequisites: [], icon_url: 'https://browiki.org/images/5/56/Aumentar_Recupera%C3%A7%C3%A3o_de_HP.png', position: { x: 4, y: 0 }, levels: lv(10, [0]) },
  { _id: S.bash, class_id: C.swordsman, name: 'Golpe Fulminante', slug: 'bash', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Ataque físico poderoso.', prerequisites: [], icon_url: 'https://browiki.org/images/5/56/Golpe_Fulminante.png', position: { x: 0, y: 2 }, levels: lv(10, [8, 8, 8, 8, 8, 15, 15, 15, 15, 15]) },
  { _id: S.provoke, class_id: C.swordsman, name: 'Provocar', slug: 'provoke', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Provoca o inimigo reduzindo DEF e aumentando ATK.', prerequisites: [], icon_url: 'https://browiki.org/images/c/ce/Provocar.png', position: { x: 2, y: 2 }, levels: lv(10, [4, 5, 6, 7, 8, 9, 10, 11, 12, 13]) },
  { _id: S.magnum_break, class_id: C.swordsman, name: 'Impacto Explosivo', slug: 'magnum-break', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Ataque em área com elemento fogo.', prerequisites: [{ skill_id: S.bash, required_level: 5 }], icon_url: 'https://browiki.org/images/6/6d/Impacto_Explosivo.png', position: { x: 0, y: 4 }, levels: lv(10, [30, 30, 30, 30, 30, 30, 30, 30, 30, 30]) },
  { _id: S.endure, class_id: C.swordsman, name: 'Vigor', slug: 'endure', type: 'buff' as const, max_level: 10, target: 'self' as const, description: 'Permite mover sem ser interrompido por ataques.', prerequisites: [], icon_url: 'https://browiki.org/images/f/f4/Vigor.png', position: { x: 4, y: 2 }, levels: lv(10, [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]) },

  // ── Knight (10) ──
  { _id: S.spear_mastery, class_id: C.knight, name: 'Perícia com Lança', slug: 'spear-mastery', type: 'passive' as const, max_level: 10, description: 'Aumenta ATK com lanças.', prerequisites: [], icon_url: 'https://browiki.org/images/6/6f/Per%C3%ADcia_com_Lan%C3%A7a.png', position: { x: 0, y: 0 }, levels: lv(10, [0]) },
  { _id: S.pierce, class_id: C.knight, name: 'Perfurar', slug: 'pierce', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Perfura o inimigo com a lança.', prerequisites: [{ skill_id: S.spear_mastery, required_level: 1 }], icon_url: 'https://browiki.org/images/5/57/Perfurar.png', position: { x: 0, y: 2 }, levels: lv(10, [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]) },
  { _id: S.brandish_spear, class_id: C.knight, name: 'Brandir Lança', slug: 'brandish-spear', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Ataque em área com lança montado.', prerequisites: [{ skill_id: S.spear_mastery, required_level: 5 }], icon_url: 'https://browiki.org/images/9/94/Brandir_Lan%C3%A7a.png', position: { x: 0, y: 4 }, levels: lv(10, [12, 12, 12, 12, 12, 12, 12, 12, 12, 12]) },
  { class_id: C.knight, name: 'Lança Bumerangue', slug: 'spear-boomerang', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Arremessa a lança à distância.', prerequisites: [{ skill_id: S.spear_mastery, required_level: 5 }], icon_url: 'https://browiki.org/images/5/53/Lan%C3%A7a_Bumerangue.png', position: { x: 1, y: 4 }, levels: lv(5, [10, 10, 10, 10, 10]) },
  { _id: S.two_hand_quicken, class_id: C.knight, name: 'Rapidez com Duas Mãos', slug: 'two-hand-quicken', type: 'buff' as const, max_level: 10, target: 'self' as const, description: 'Aumenta ASPD com espada de duas mãos.', prerequisites: [{ skill_id: S.twohand_mastery, required_level: 10 }], icon_url: 'https://browiki.org/images/9/93/Rapidez_com_Duas_M%C3%A3os.png', position: { x: 3, y: 0 }, levels: lv(10, [14, 14, 14, 14, 14, 14, 14, 14, 14, 14]) },
  { _id: S.auto_counter, class_id: C.knight, name: 'Contra-Ataque', slug: 'auto-counter', type: 'passive' as const, max_level: 5, description: 'Contra-ataca automaticamente.', prerequisites: [{ skill_id: S.bash, required_level: 5 }], icon_url: 'https://browiki.org/images/b/be/Contra-Ataque.png', position: { x: 2, y: 0 }, levels: lv(5, [0]) },
  { _id: S.bowling_bash, class_id: C.knight, name: 'Avanço Ofensivo', slug: 'bowling-bash', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Ataque devastador que empurra inimigos.', prerequisites: [{ skill_id: S.bash, required_level: 5 }, { skill_id: S.two_hand_quicken, required_level: 1 }], icon_url: 'https://browiki.org/images/3/3f/Avan%C3%A7o_Ofensivo.png', position: { x: 3, y: 2 }, levels: lv(10, [13, 14, 15, 16, 17, 18, 19, 20, 21, 22]) },
  { _id: S.riding, class_id: C.knight, name: 'Montaria', slug: 'riding', type: 'passive' as const, max_level: 1, description: 'Permite montar em Pecopeco.', prerequisites: [], icon_url: 'https://browiki.org/images/c/c4/Montaria.png', position: { x: 4, y: 0 }, levels: lv(1, [0]) },
  { _id: S.cavalry_mastery, class_id: C.knight, name: 'Perícia em Montaria', slug: 'cavalry-mastery', type: 'passive' as const, max_level: 5, description: 'Reduz penalidade de ASPD montado.', prerequisites: [{ skill_id: S.riding, required_level: 1 }], icon_url: 'https://browiki.org/images/4/46/Per%C3%ADcia_em_Montaria.png', position: { x: 4, y: 2 }, levels: lv(5, [0]) },
  { _id: S.head_crush, class_id: C.knight, name: 'Ataque Vital', slug: 'head-crush', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Causa sangramento no inimigo.', prerequisites: [], icon_url: 'https://browiki.org/images/b/ba/Ataque_Vital.png', position: { x: 2, y: 2 }, levels: lv(5, [23, 23, 23, 23, 23]) },

  // ── Crusader (9) ──
  { _id: S.guard, class_id: C.crusader, name: 'Bloqueio', slug: 'guard', type: 'passive' as const, max_level: 10, description: 'Chance de bloquear ataques com escudo.', prerequisites: [], icon_url: 'https://browiki.org/images/8/85/Bloqueio.png', position: { x: 0, y: 0 }, levels: lv(10, [0]) },
  { class_id: C.crusader, name: 'Punição Divina', slug: 'smite', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Ataque com escudo que empurra.', prerequisites: [{ skill_id: S.guard, required_level: 5 }], icon_url: 'https://browiki.org/images/0/0c/Puni%C3%A7%C3%A3o_Divina.png', position: { x: 0, y: 2 }, levels: lv(5, [10, 10, 10, 10, 10]) },
  { class_id: C.crusader, name: 'Escudo Bumerangue', slug: 'shield-boomerang', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Arremessa o escudo no inimigo.', prerequisites: [{ skill_id: S.guard, required_level: 5 }], icon_url: 'https://browiki.org/images/2/2d/Escudo_Bumerangue.png', position: { x: 1, y: 2 }, levels: lv(5, [12, 12, 12, 12, 12]) },
  { _id: S.holy_cross, class_id: C.crusader, name: 'Crux Divinum', slug: 'holy-cross', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Ataque em forma de cruz sagrada.', prerequisites: [], icon_url: 'https://browiki.org/images/d/db/Crux_Divinum.png', position: { x: 2, y: 0 }, levels: lv(10, [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]) },
  { class_id: C.crusader, name: 'Crux Magnum', slug: 'grand-cross', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Cria uma cruz massiva de dano sagrado.', prerequisites: [{ skill_id: S.holy_cross, required_level: 5 }], icon_url: 'https://browiki.org/images/8/83/Crux_Magnum.png', position: { x: 2, y: 2 }, levels: lv(10, [37, 37, 37, 37, 37, 37, 37, 37, 37, 37]) },
  { class_id: C.crusader, name: 'Fé', slug: 'resistant-souls', type: 'passive' as const, max_level: 5, description: 'Aumenta resistência a propriedades.', prerequisites: [], icon_url: 'https://browiki.org/images/7/70/F%C3%A9.png', position: { x: 3, y: 0 }, levels: lv(5, [0]) },
  { class_id: C.crusader, name: 'Submissão', slug: 'shrink', type: 'passive' as const, max_level: 1, description: 'Empurra inimigo ao bloquear.', prerequisites: [], icon_url: 'https://browiki.org/images/4/4c/Submiss%C3%A3o.png', position: { x: 1, y: 0 }, levels: lv(1, [0]) },
  { class_id: C.crusader, name: 'Rapidez com Lança', slug: 'spear-quicken', type: 'buff' as const, max_level: 10, target: 'self' as const, description: 'Aumenta ASPD com lanças.', prerequisites: [{ skill_id: S.spear_mastery, required_level: 5 }], icon_url: 'https://browiki.org/images/a/a9/Rapidez_com_Lan%C3%A7a.png', position: { x: 4, y: 0 }, levels: lv(10, [24, 24, 24, 24, 24, 24, 24, 24, 24, 24]) },
  { class_id: C.crusader, name: 'Redenção', slug: 'devotion', type: 'support' as const, max_level: 5, target: 'ally' as const, description: 'Absorve dano de um aliado.', prerequisites: [], icon_url: 'https://browiki.org/images/a/ac/Reden%C3%A7%C3%A3o.png', position: { x: 4, y: 2 }, levels: lv(5, [25, 25, 25, 25, 25]) },

  // ── Lord Knight (6) ──
  { class_id: C.lord_knight, name: 'Aparar Golpe', slug: 'parry', type: 'passive' as const, max_level: 10, description: 'Chance de parar ataques com espada de duas mãos.', prerequisites: [], icon_url: 'https://browiki.org/images/0/04/Aparar_Golpe.png', position: { x: 0, y: 0 }, levels: lv(10, [0]) },
  { class_id: C.lord_knight, name: 'Perfurar em Espiral', slug: 'spiral-pierce', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Ataque espiral com lança baseado no peso.', prerequisites: [], icon_url: 'https://browiki.org/images/0/0b/Perfurar_em_Espiral.png', position: { x: 1, y: 0 }, levels: lv(5, [18, 21, 24, 27, 30]) },
  { class_id: C.lord_knight, name: 'Rapidez com Uma Mão', slug: 'one-hand-quicken', type: 'buff' as const, max_level: 5, target: 'self' as const, description: 'Aumenta ASPD com espada de uma mão.', prerequisites: [], icon_url: 'https://browiki.org/images/3/37/Rapidez_com_Uma_M%C3%A3o.png', position: { x: 2, y: 0 }, levels: lv(5, [14, 14, 14, 14, 14]) },
  { class_id: C.lord_knight, name: 'Golpe Traumático', slug: 'traumatic-blow', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Ataque que causa sangramento.', prerequisites: [], icon_url: 'https://browiki.org/images/4/46/Golpe_Traum%C3%A1tico.png', position: { x: 3, y: 0 }, levels: lv(5, [20, 20, 20, 20, 20]) },
  { class_id: C.lord_knight, name: 'Frenesi', slug: 'frenzy', type: 'buff' as const, max_level: 1, target: 'self' as const, description: 'Sacrifica defesa por poder extremo.', prerequisites: [], icon_url: 'https://browiki.org/images/d/de/Frenesi.png', position: { x: 4, y: 0 }, levels: lv(1, [200]) },
  { class_id: C.lord_knight, name: 'Avanço Ofensivo', slug: 'charge-attack', type: 'active' as const, max_level: 1, target: 'enemy' as const, description: 'Investida à distância.', prerequisites: [], icon_url: 'https://browiki.org/images/3/3f/Avan%C3%A7o_Ofensivo.png', position: { x: 4, y: 2 }, levels: lv(1, [40]) },

  // ── Paladin (6) ──
  { class_id: C.paladin, name: 'Sacrifício do Mártir', slug: 'sacrifice', type: 'buff' as const, max_level: 5, target: 'self' as const, description: 'Usa HP próprio para atacar.', prerequisites: [], icon_url: 'https://browiki.org/images/9/91/Sacrif%C3%ADcio_do_M%C3%A1rtir.png', position: { x: 0, y: 0 }, levels: lv(5, [100, 100, 100, 100, 100]) },
  { class_id: C.paladin, name: 'Escudo Refletor', slug: 'reflect-shield', type: 'buff' as const, max_level: 10, target: 'self' as const, description: 'Reflete dano físico ao atacante.', prerequisites: [], icon_url: 'https://browiki.org/images/7/77/Escudo_Refletor.png', position: { x: 1, y: 0 }, levels: lv(10, [35, 35, 35, 35, 35, 35, 35, 35, 35, 35]) },
  { class_id: C.paladin, name: 'Gloria Domini', slug: 'pressure', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Ataque à distância que ignora defesa.', prerequisites: [], icon_url: 'https://browiki.org/images/f/ff/Gloria_Domini.png', position: { x: 2, y: 0 }, levels: lv(5, [22, 24, 26, 28, 30]) },
  { class_id: C.paladin, name: 'Proteção Divina', slug: 'defender', type: 'buff' as const, max_level: 5, target: 'self' as const, description: 'Reduz dano ranged massivamente.', prerequisites: [], icon_url: 'https://browiki.org/images/4/45/Prote%C3%A7%C3%A3o_Divina.png', position: { x: 3, y: 0 }, levels: lv(5, [30, 30, 30, 30, 30]) },
  { class_id: C.paladin, name: 'Canto de Batalha', slug: 'battle-chant', type: 'buff' as const, max_level: 10, target: 'area' as const, description: 'Efeitos aleatórios benéficos para o grupo.', prerequisites: [], icon_url: 'https://browiki.org/images/8/8f/Canto_de_Batalha.png', position: { x: 4, y: 0 }, levels: lv(10, [50, 50, 50, 50, 50, 50, 50, 50, 50, 50]) },
  { class_id: C.paladin, name: 'Choque Rápido', slug: 'rapid-smiting', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Ataque rápido com escudo.', prerequisites: [], icon_url: 'https://browiki.org/images/f/ff/Choque_R%C3%A1pido.png', position: { x: 4, y: 2 }, levels: lv(5, [16, 16, 16, 16, 16]) },

  // ── Rune Knight (6) ──
  { class_id: C.rune_knight, name: 'Adestrar Dragão', slug: 'dragon-training', type: 'passive' as const, max_level: 5, description: 'Permite montar dragão e aumenta poder.', prerequisites: [], icon_url: 'https://browiki.org/images/0/07/Adestrar_Drag%C3%A3o.png', position: { x: 0, y: 0 }, levels: lv(5, [0]) },
  { class_id: C.rune_knight, name: 'Bafo do Dragão', slug: 'dragon-breath', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Sopro de fogo do dragão.', prerequisites: [], icon_url: 'https://browiki.org/images/5/5d/Bafo_do_Drag%C3%A3o.png', position: { x: 1, y: 0 }, levels: lv(10, [30, 35, 40, 45, 50, 55, 60, 65, 70, 75]) },
  { class_id: C.rune_knight, name: 'Lança das Mil Pontas', slug: 'hundred-spears', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Múltiplos golpes de lança.', prerequisites: [], icon_url: 'https://browiki.org/images/f/f9/Lan%C3%A7a_das_Mil_Pontas.png', position: { x: 2, y: 0 }, levels: lv(10, [60, 60, 60, 60, 60, 60, 60, 60, 60, 60]) },
  { class_id: C.rune_knight, name: 'Impacto Flamejante', slug: 'ignition-break', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Explosão de fogo em área.', prerequisites: [], icon_url: 'https://browiki.org/images/8/85/Impacto_Flamejante.png', position: { x: 3, y: 0 }, levels: lv(10, [35, 38, 41, 44, 47, 50, 53, 56, 59, 62]) },
  { class_id: C.rune_knight, name: 'Onda de Choque', slug: 'sonic-wave', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Onda sônica à distância.', prerequisites: [], icon_url: 'https://browiki.org/images/4/44/Onda_de_Choque.png', position: { x: 4, y: 0 }, levels: lv(10, [20, 24, 28, 32, 36, 40, 44, 48, 52, 56]) },
  { class_id: C.rune_knight, name: 'Revidar Dano', slug: 'death-bound', type: 'active' as const, max_level: 10, target: 'self' as const, description: 'Reflete dano amplificado ao atacante.', prerequisites: [], icon_url: 'https://browiki.org/images/9/91/Revidar_Dano.png', position: { x: 4, y: 2 }, levels: lv(10, [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]) },

  // ── Royal Guard (6) ──
  { class_id: C.royal_guard, name: 'Formação Real', slug: 'banding', type: 'support' as const, max_level: 5, target: 'area' as const, description: 'Ligação com outros Royal Guards.', prerequisites: [], icon_url: 'https://browiki.org/images/5/59/Forma%C3%A7%C3%A3o_Real.png', position: { x: 0, y: 0 }, levels: lv(5, [20, 24, 28, 32, 36]) },
  { class_id: C.royal_guard, name: 'Disparo Perfurante', slug: 'cannon-spear', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Dispara projétil de lança.', prerequisites: [], icon_url: 'https://browiki.org/images/0/07/Disparo_Perfurante.png', position: { x: 1, y: 0 }, levels: lv(5, [30, 30, 30, 30, 30]) },
  { class_id: C.royal_guard, name: 'Estocada Precisa', slug: 'pinpoint-attack', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Ataque preciso que quebra equipamento.', prerequisites: [], icon_url: 'https://browiki.org/images/7/78/Estocada_Precisa.png', position: { x: 2, y: 0 }, levels: lv(5, [15, 15, 15, 15, 15]) },
  { class_id: C.royal_guard, name: 'Prestígio Divino', slug: 'prestige', type: 'buff' as const, max_level: 10, target: 'self' as const, description: 'Aumenta DEF e MDEF temporariamente.', prerequisites: [], icon_url: 'https://browiki.org/images/2/24/Prest%C3%ADgio_Divino.png', position: { x: 3, y: 0 }, levels: lv(10, [30, 32, 34, 36, 38, 40, 42, 44, 46, 48]) },
  { class_id: C.royal_guard, name: 'Consagração', slug: 'piety', type: 'buff' as const, max_level: 5, target: 'area' as const, description: 'Encanta armas do grupo com propriedade sagrada.', prerequisites: [], icon_url: 'https://browiki.org/images/3/3d/Consagra%C3%A7%C3%A3o.png', position: { x: 4, y: 0 }, levels: lv(5, [40, 40, 40, 40, 40]) },
  { class_id: C.royal_guard, name: 'Aegis Domini', slug: 'aegis', type: 'buff' as const, max_level: 5, target: 'self' as const, description: 'Barreira mágica protetora.', prerequisites: [], icon_url: 'https://browiki.org/images/e/ea/Aegis_Domini.png', position: { x: 4, y: 2 }, levels: lv(5, [30, 30, 30, 30, 30]) },
]
