import { C, S, lv, dp } from './shared'

export const swordsmanChainSkills = [
  // ── Swordsman (7) ──
  { _id: S.sword_mastery, class_id: C.swordsman, name: 'Sword Mastery', slug: 'sword-mastery', type: 'passive' as const, max_level: 10, description: 'Aumenta ATK com espadas.', prerequisites: [], icon_url: dp(2), position: { x: 0, y: 0 }, levels: lv(10, [0]) },
  { _id: S.twohand_mastery, class_id: C.swordsman, name: 'Two-Hand Sword Mastery', slug: 'twohand-sword-mastery', type: 'passive' as const, max_level: 10, description: 'Aumenta ATK com espadas de duas mãos.', prerequisites: [], icon_url: dp(3), position: { x: 2, y: 0 }, levels: lv(10, [0]) },
  { _id: S.hp_recovery, class_id: C.swordsman, name: 'Increase HP Recovery', slug: 'increase-hp-recovery', type: 'passive' as const, max_level: 10, description: 'Aumenta recuperação natural de HP.', prerequisites: [], icon_url: dp(4), position: { x: 4, y: 0 }, levels: lv(10, [0]) },
  { _id: S.bash, class_id: C.swordsman, name: 'Bash', slug: 'bash', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Ataque físico poderoso.', prerequisites: [], icon_url: dp(5), position: { x: 0, y: 2 }, levels: lv(10, [8, 8, 8, 8, 8, 15, 15, 15, 15, 15]) },
  { _id: S.provoke, class_id: C.swordsman, name: 'Provoke', slug: 'provoke', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Provoca o inimigo reduzindo DEF e aumentando ATK.', prerequisites: [], icon_url: dp(6), position: { x: 2, y: 2 }, levels: lv(10, [4, 5, 6, 7, 8, 9, 10, 11, 12, 13]) },
  { _id: S.magnum_break, class_id: C.swordsman, name: 'Magnum Break', slug: 'magnum-break', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Ataque em área com elemento fogo.', prerequisites: [{ skill_id: S.bash, required_level: 5 }], icon_url: dp(7), position: { x: 0, y: 4 }, levels: lv(10, [30, 30, 30, 30, 30, 30, 30, 30, 30, 30]) },
  { _id: S.endure, class_id: C.swordsman, name: 'Endure', slug: 'endure', type: 'buff' as const, max_level: 10, target: 'self' as const, description: 'Permite mover sem ser interrompido por ataques.', prerequisites: [], icon_url: dp(8), position: { x: 4, y: 2 }, levels: lv(10, [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]) },

  // ── Knight (10) ──
  { _id: S.spear_mastery, class_id: C.knight, name: 'Spear Mastery', slug: 'spear-mastery', type: 'passive' as const, max_level: 10, description: 'Aumenta ATK com lanças.', prerequisites: [], icon_url: dp(55), position: { x: 0, y: 0 }, levels: lv(10, [0]) },
  { _id: S.pierce, class_id: C.knight, name: 'Pierce', slug: 'pierce', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Perfura o inimigo com a lança.', prerequisites: [{ skill_id: S.spear_mastery, required_level: 1 }], icon_url: dp(56), position: { x: 0, y: 2 }, levels: lv(10, [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]) },
  { _id: S.brandish_spear, class_id: C.knight, name: 'Brandish Spear', slug: 'brandish-spear', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Ataque em área com lança montado.', prerequisites: [{ skill_id: S.spear_mastery, required_level: 5 }], icon_url: dp(57), position: { x: 0, y: 4 }, levels: lv(10, [12, 12, 12, 12, 12, 12, 12, 12, 12, 12]) },
  { class_id: C.knight, name: 'Spear Boomerang', slug: 'spear-boomerang', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Arremessa a lança à distância.', prerequisites: [{ skill_id: S.spear_mastery, required_level: 5 }], icon_url: dp(58), position: { x: 1, y: 4 }, levels: lv(5, [10, 10, 10, 10, 10]) },
  { _id: S.two_hand_quicken, class_id: C.knight, name: 'Two-Hand Quicken', slug: 'two-hand-quicken', type: 'buff' as const, max_level: 10, target: 'self' as const, description: 'Aumenta ASPD com espada de duas mãos.', prerequisites: [{ skill_id: S.twohand_mastery, required_level: 10 }], icon_url: dp(59), position: { x: 3, y: 0 }, levels: lv(10, [14, 14, 14, 14, 14, 14, 14, 14, 14, 14]) },
  { _id: S.auto_counter, class_id: C.knight, name: 'Auto Counter', slug: 'auto-counter', type: 'passive' as const, max_level: 5, description: 'Contra-ataca automaticamente.', prerequisites: [{ skill_id: S.bash, required_level: 5 }], icon_url: dp(60), position: { x: 2, y: 0 }, levels: lv(5, [0]) },
  { _id: S.bowling_bash, class_id: C.knight, name: 'Bowling Bash', slug: 'bowling-bash', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Ataque devastador que empurra inimigos.', prerequisites: [{ skill_id: S.bash, required_level: 5 }, { skill_id: S.two_hand_quicken, required_level: 1 }], icon_url: dp(62), position: { x: 3, y: 2 }, levels: lv(10, [13, 14, 15, 16, 17, 18, 19, 20, 21, 22]) },
  { _id: S.riding, class_id: C.knight, name: 'Riding', slug: 'riding', type: 'passive' as const, max_level: 1, description: 'Permite montar em Pecopeco.', prerequisites: [], icon_url: dp(63), position: { x: 4, y: 0 }, levels: lv(1, [0]) },
  { _id: S.cavalry_mastery, class_id: C.knight, name: 'Cavalry Mastery', slug: 'cavalry-mastery', type: 'passive' as const, max_level: 5, description: 'Reduz penalidade de ASPD montado.', prerequisites: [{ skill_id: S.riding, required_level: 1 }], icon_url: dp(64), position: { x: 4, y: 2 }, levels: lv(5, [0]) },
  { _id: S.head_crush, class_id: C.knight, name: 'Head Crush', slug: 'head-crush', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Causa sangramento no inimigo.', prerequisites: [], icon_url: dp(65), position: { x: 2, y: 2 }, levels: lv(5, [23, 23, 23, 23, 23]) },

  // ── Crusader (9) ──
  { _id: S.guard, class_id: C.crusader, name: 'Guard', slug: 'guard', type: 'passive' as const, max_level: 10, description: 'Chance de bloquear ataques com escudo.', prerequisites: [], icon_url: dp(248), position: { x: 0, y: 0 }, levels: lv(10, [0]) },
  { class_id: C.crusader, name: 'Smite', slug: 'smite', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Ataque com escudo que empurra.', prerequisites: [{ skill_id: S.guard, required_level: 5 }], icon_url: dp(249), position: { x: 0, y: 2 }, levels: lv(5, [10, 10, 10, 10, 10]) },
  { class_id: C.crusader, name: 'Shield Boomerang', slug: 'shield-boomerang', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Arremessa o escudo no inimigo.', prerequisites: [{ skill_id: S.guard, required_level: 5 }], icon_url: dp(250), position: { x: 1, y: 2 }, levels: lv(5, [12, 12, 12, 12, 12]) },
  { _id: S.holy_cross, class_id: C.crusader, name: 'Holy Cross', slug: 'holy-cross', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Ataque em forma de cruz sagrada.', prerequisites: [], icon_url: dp(253), position: { x: 2, y: 0 }, levels: lv(10, [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]) },
  { class_id: C.crusader, name: 'Grand Cross', slug: 'grand-cross', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Cria uma cruz massiva de dano sagrado.', prerequisites: [{ skill_id: S.holy_cross, required_level: 5 }], icon_url: dp(254), position: { x: 2, y: 2 }, levels: lv(10, [37, 37, 37, 37, 37, 37, 37, 37, 37, 37]) },
  { class_id: C.crusader, name: 'Resistant Souls', slug: 'resistant-souls', type: 'passive' as const, max_level: 5, description: 'Aumenta resistência a propriedades.', prerequisites: [], icon_url: dp(255), position: { x: 3, y: 0 }, levels: lv(5, [0]) },
  { class_id: C.crusader, name: 'Shrink', slug: 'shrink', type: 'passive' as const, max_level: 1, description: 'Empurra inimigo ao bloquear.', prerequisites: [], icon_url: dp(256), position: { x: 1, y: 0 }, levels: lv(1, [0]) },
  { class_id: C.crusader, name: 'Spear Quicken', slug: 'spear-quicken', type: 'buff' as const, max_level: 10, target: 'self' as const, description: 'Aumenta ASPD com lanças.', prerequisites: [{ skill_id: S.spear_mastery, required_level: 5 }], icon_url: dp(257), position: { x: 4, y: 0 }, levels: lv(10, [24, 24, 24, 24, 24, 24, 24, 24, 24, 24]) },
  { class_id: C.crusader, name: 'Devotion', slug: 'devotion', type: 'support' as const, max_level: 5, target: 'ally' as const, description: 'Absorve dano de um aliado.', prerequisites: [], icon_url: dp(258), position: { x: 4, y: 2 }, levels: lv(5, [25, 25, 25, 25, 25]) },

  // ── Lord Knight (6) ──
  { class_id: C.lord_knight, name: 'Parry', slug: 'parry', type: 'passive' as const, max_level: 10, description: 'Chance de parar ataques com espada de duas mãos.', prerequisites: [], icon_url: dp(355), position: { x: 0, y: 0 }, levels: lv(10, [0]) },
  { class_id: C.lord_knight, name: 'Spiral Pierce', slug: 'spiral-pierce', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Ataque espiral com lança baseado no peso.', prerequisites: [], icon_url: dp(397), position: { x: 1, y: 0 }, levels: lv(5, [18, 21, 24, 27, 30]) },
  { class_id: C.lord_knight, name: 'One-Hand Quicken', slug: 'one-hand-quicken', type: 'buff' as const, max_level: 5, target: 'self' as const, description: 'Aumenta ASPD com espada de uma mão.', prerequisites: [], icon_url: dp(398), position: { x: 2, y: 0 }, levels: lv(5, [14, 14, 14, 14, 14]) },
  { class_id: C.lord_knight, name: 'Traumatic Blow', slug: 'traumatic-blow', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Ataque que causa sangramento.', prerequisites: [], icon_url: dp(399), position: { x: 3, y: 0 }, levels: lv(5, [20, 20, 20, 20, 20]) },
  { class_id: C.lord_knight, name: 'Frenzy', slug: 'frenzy', type: 'buff' as const, max_level: 1, target: 'self' as const, description: 'Sacrifica defesa por poder extremo.', prerequisites: [], icon_url: dp(356), position: { x: 4, y: 0 }, levels: lv(1, [200]) },
  { class_id: C.lord_knight, name: 'Charge Attack', slug: 'charge-attack', type: 'active' as const, max_level: 1, target: 'enemy' as const, description: 'Investida à distância.', prerequisites: [], icon_url: dp(357), position: { x: 4, y: 2 }, levels: lv(1, [40]) },

  // ── Paladin (6) ──
  { class_id: C.paladin, name: 'Sacrifice', slug: 'sacrifice', type: 'buff' as const, max_level: 5, target: 'self' as const, description: 'Usa HP próprio para atacar.', prerequisites: [], icon_url: dp(358), position: { x: 0, y: 0 }, levels: lv(5, [100, 100, 100, 100, 100]) },
  { class_id: C.paladin, name: 'Reflect Shield', slug: 'reflect-shield', type: 'buff' as const, max_level: 10, target: 'self' as const, description: 'Reflete dano físico ao atacante.', prerequisites: [], icon_url: dp(252), position: { x: 1, y: 0 }, levels: lv(10, [35, 35, 35, 35, 35, 35, 35, 35, 35, 35]) },
  { class_id: C.paladin, name: 'Pressure', slug: 'pressure', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Ataque à distância que ignora defesa.', prerequisites: [], icon_url: dp(359), position: { x: 2, y: 0 }, levels: lv(5, [22, 24, 26, 28, 30]) },
  { class_id: C.paladin, name: 'Defender', slug: 'defender', type: 'buff' as const, max_level: 5, target: 'self' as const, description: 'Reduz dano ranged massivamente.', prerequisites: [], icon_url: dp(251), position: { x: 3, y: 0 }, levels: lv(5, [30, 30, 30, 30, 30]) },
  { class_id: C.paladin, name: 'Battle Chant', slug: 'battle-chant', type: 'buff' as const, max_level: 10, target: 'area' as const, description: 'Efeitos aleatórios benéficos para o grupo.', prerequisites: [], icon_url: dp(360), position: { x: 4, y: 0 }, levels: lv(10, [50, 50, 50, 50, 50, 50, 50, 50, 50, 50]) },
  { class_id: C.paladin, name: 'Rapid Smiting', slug: 'rapid-smiting', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Ataque rápido com escudo.', prerequisites: [], icon_url: dp(361), position: { x: 4, y: 2 }, levels: lv(5, [16, 16, 16, 16, 16]) },

  // ── Rune Knight (6) ──
  { class_id: C.rune_knight, name: 'Dragon Training', slug: 'dragon-training', type: 'passive' as const, max_level: 5, description: 'Permite montar dragão e aumenta poder.', prerequisites: [], icon_url: dp(2010), position: { x: 0, y: 0 }, levels: lv(5, [0]) },
  { class_id: C.rune_knight, name: 'Dragon Breath', slug: 'dragon-breath', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Sopro de fogo do dragão.', prerequisites: [], icon_url: dp(2017), position: { x: 1, y: 0 }, levels: lv(10, [30, 35, 40, 45, 50, 55, 60, 65, 70, 75]) },
  { class_id: C.rune_knight, name: 'Hundred Spears', slug: 'hundred-spears', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Múltiplos golpes de lança.', prerequisites: [], icon_url: dp(2015), position: { x: 2, y: 0 }, levels: lv(10, [60, 60, 60, 60, 60, 60, 60, 60, 60, 60]) },
  { class_id: C.rune_knight, name: 'Ignition Break', slug: 'ignition-break', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Explosão de fogo em área.', prerequisites: [], icon_url: dp(2018), position: { x: 3, y: 0 }, levels: lv(10, [35, 38, 41, 44, 47, 50, 53, 56, 59, 62]) },
  { class_id: C.rune_knight, name: 'Sonic Wave', slug: 'sonic-wave', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Onda sônica à distância.', prerequisites: [], icon_url: dp(2019), position: { x: 4, y: 0 }, levels: lv(10, [20, 24, 28, 32, 36, 40, 44, 48, 52, 56]) },
  { class_id: C.rune_knight, name: 'Death Bound', slug: 'death-bound', type: 'active' as const, max_level: 10, target: 'self' as const, description: 'Reflete dano amplificado ao atacante.', prerequisites: [], icon_url: dp(2020), position: { x: 4, y: 2 }, levels: lv(10, [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]) },

  // ── Royal Guard (6) ──
  { class_id: C.royal_guard, name: 'Banding', slug: 'banding', type: 'support' as const, max_level: 5, target: 'area' as const, description: 'Ligação com outros Royal Guards.', prerequisites: [], icon_url: dp(2024), position: { x: 0, y: 0 }, levels: lv(5, [20, 24, 28, 32, 36]) },
  { class_id: C.royal_guard, name: 'Cannon Spear', slug: 'cannon-spear', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Dispara projétil de lança.', prerequisites: [], icon_url: dp(2025), position: { x: 1, y: 0 }, levels: lv(5, [30, 30, 30, 30, 30]) },
  { class_id: C.royal_guard, name: 'Pinpoint Attack', slug: 'pinpoint-attack', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Ataque preciso que quebra equipamento.', prerequisites: [], icon_url: dp(2026), position: { x: 2, y: 0 }, levels: lv(5, [15, 15, 15, 15, 15]) },
  { class_id: C.royal_guard, name: 'Prestige', slug: 'prestige', type: 'buff' as const, max_level: 10, target: 'self' as const, description: 'Aumenta DEF e MDEF temporariamente.', prerequisites: [], icon_url: dp(2027), position: { x: 3, y: 0 }, levels: lv(10, [30, 32, 34, 36, 38, 40, 42, 44, 46, 48]) },
  { class_id: C.royal_guard, name: 'Piety', slug: 'piety', type: 'buff' as const, max_level: 5, target: 'area' as const, description: 'Encanta armas do grupo com propriedade sagrada.', prerequisites: [], icon_url: dp(2028), position: { x: 4, y: 0 }, levels: lv(5, [40, 40, 40, 40, 40]) },
  { class_id: C.royal_guard, name: 'Aegis', slug: 'aegis', type: 'buff' as const, max_level: 5, target: 'self' as const, description: 'Barreira mágica protetora.', prerequisites: [], icon_url: dp(2029), position: { x: 4, y: 2 }, levels: lv(5, [30, 30, 30, 30, 30]) },
]
