import { C, S, lv, dp } from './shared'

export const acolyteChainSkills = [
  // ── Acolyte (8) ──
  { _id: S.divine_protection, class_id: C.acolyte, name: 'Proteção Divina', slug: 'divine-protection', type: 'passive' as const, max_level: 10, description: 'Reduz dano de Undead e Demon.', prerequisites: [], icon_url: 'https://browiki.org/images/4/45/Prote%C3%A7%C3%A3o_Divina.png', position: { x: 0, y: 0 }, levels: lv(10, [0]) },
  { _id: S.demon_bane, class_id: C.acolyte, name: 'Flagelo do Mal', slug: 'demon-bane', type: 'passive' as const, max_level: 10, description: 'Dano extra contra Undead e Demon.', prerequisites: [], icon_url: 'https://browiki.org/images/f/fb/Flagelo_do_Mal.png', position: { x: 2, y: 0 }, levels: lv(10, [0]) },
  { class_id: C.acolyte, name: 'Revelação', slug: 'ruwach', type: 'active' as const, max_level: 1, target: 'area' as const, description: 'Revela inimigos escondidos.', prerequisites: [], icon_url: 'https://browiki.org/images/9/92/Revela%C3%A7%C3%A3o.png', position: { x: 4, y: 0 }, levels: lv(1, [10]) },
  { class_id: C.acolyte, name: 'Escudo Sagrado', slug: 'pneuma', type: 'support' as const, max_level: 1, target: 'area' as const, description: 'Bloqueia ataques ranged na área.', prerequisites: [], icon_url: 'https://browiki.org/images/b/b5/Escudo_Sagrado.png', position: { x: 4, y: 2 }, levels: lv(1, [10]) },
  { _id: S.heal, class_id: C.acolyte, name: 'Curar', slug: 'heal', type: 'active' as const, max_level: 10, target: 'ally' as const, description: 'Cura HP de um aliado.', prerequisites: [], icon_url: 'https://browiki.org/images/c/c1/Curar.png', position: { x: 0, y: 2 }, levels: lv(10, [13, 16, 19, 22, 25, 28, 31, 34, 37, 40]) },
  { _id: S.increase_agi, class_id: C.acolyte, name: 'Aumentar Agilidade', slug: 'increase-agi', type: 'buff' as const, max_level: 10, target: 'ally' as const, description: 'Aumenta AGI e velocidade do alvo.', prerequisites: [], icon_url: 'https://browiki.org/images/d/d9/Aumentar_Agilidade.png', position: { x: 1, y: 2 }, levels: lv(10, [18, 21, 24, 27, 30, 33, 36, 39, 42, 45]) },
  { class_id: C.acolyte, name: 'Diminuir Agilidade', slug: 'decrease-agi', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Reduz AGI e velocidade do inimigo.', prerequisites: [], icon_url: 'https://browiki.org/images/3/38/Diminuir_Agilidade.png', position: { x: 2, y: 2 }, levels: lv(10, [18, 21, 24, 27, 30, 33, 36, 39, 42, 45]) },
  { _id: S.blessing, class_id: C.acolyte, name: 'Bênção', slug: 'blessing', type: 'buff' as const, max_level: 10, target: 'ally' as const, description: 'Aumenta STR, DEX e INT do alvo.', prerequisites: [], icon_url: 'https://browiki.org/images/8/81/B%C3%AAn%C3%A7%C3%A3o.png', position: { x: 3, y: 2 }, levels: lv(10, [28, 32, 36, 40, 44, 48, 52, 56, 60, 64]) },

  // ── Priest (10) ──
  { class_id: C.priest, name: 'Aspersio', slug: 'aspersio', type: 'buff' as const, max_level: 5, target: 'ally' as const, description: 'Encanta arma com propriedade sagrada.', prerequisites: [], icon_url: 'https://browiki.org/images/7/70/Aspersio.png', position: { x: 0, y: 0 }, levels: lv(5, [14, 18, 22, 26, 30]) },
  { class_id: C.priest, name: 'Luz Divina', slug: 'holy-light', type: 'active' as const, max_level: 1, target: 'enemy' as const, description: 'Ataque sagrado básico.', prerequisites: [], icon_url: 'https://browiki.org/images/9/97/Luz_Divina.png', position: { x: 0, y: 2 }, levels: lv(1, [15]) },
  { class_id: C.priest, name: 'Impositio Manus', slug: 'impositio-manus', type: 'buff' as const, max_level: 5, target: 'ally' as const, description: 'Aumenta ATK do alvo.', prerequisites: [], icon_url: 'https://browiki.org/images/7/71/Impositio_Manus.png', position: { x: 1, y: 0 }, levels: lv(5, [13, 16, 19, 22, 25]) },
  { class_id: C.priest, name: 'Magnificat', slug: 'magnificat', type: 'buff' as const, max_level: 5, target: 'area' as const, description: 'Dobra recuperação de SP do grupo.', prerequisites: [], icon_url: 'https://browiki.org/images/7/73/Magnificat.png', position: { x: 2, y: 0 }, levels: lv(5, [40, 40, 40, 40, 40]) },
  { class_id: C.priest, name: 'Ressuscitar', slug: 'resurrection', type: 'active' as const, max_level: 4, target: 'ally' as const, description: 'Revive um aliado morto.', prerequisites: [], icon_url: 'https://browiki.org/images/3/34/Ressuscitar.png', position: { x: 3, y: 0 }, levels: lv(4, [60, 60, 60, 60]) },
  { class_id: C.priest, name: 'Glória', slug: 'gloria', type: 'buff' as const, max_level: 5, target: 'area' as const, description: 'Aumenta LUK do grupo.', prerequisites: [], icon_url: 'https://browiki.org/images/3/39/Gl%C3%B3ria.png', position: { x: 4, y: 0 }, levels: lv(5, [20, 20, 20, 20, 20]) },
  { class_id: C.priest, name: 'Santuário', slug: 'sanctuary', type: 'support' as const, max_level: 10, target: 'area' as const, description: 'Área de cura contínua.', prerequisites: [], icon_url: 'https://browiki.org/images/2/20/Santu%C3%A1rio.png', position: { x: 1, y: 2 }, levels: lv(10, [15, 18, 21, 24, 27, 30, 33, 36, 39, 42]) },
  { _id: S.lex_divina, class_id: C.priest, name: 'Lex Divina', slug: 'lex-divina', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Silencia o inimigo.', prerequisites: [], icon_url: 'https://browiki.org/images/c/c4/Lex_Divina.png', position: { x: 2, y: 2 }, levels: lv(10, [20, 20, 20, 20, 20, 20, 20, 20, 20, 20]) },
  { class_id: C.priest, name: 'Lex Aeterna', slug: 'lex-aeterna', type: 'active' as const, max_level: 1, target: 'enemy' as const, description: 'Dobra o próximo dano no alvo.', prerequisites: [], icon_url: 'https://browiki.org/images/3/35/Lex_Aeterna.png', position: { x: 3, y: 2 }, levels: lv(1, [10]) },
  { class_id: C.priest, name: 'Magnus Exorcismus', slug: 'magnus-exorcismus', type: 'active' as const, max_level: 10, target: 'area' as const, description: 'Cruz sagrada que devasta undead.', prerequisites: [{ skill_id: S.lex_divina, required_level: 5 }], icon_url: 'https://browiki.org/images/8/8f/Magnus_Exorcismus.png', position: { x: 4, y: 2 }, levels: lv(10, [40, 42, 44, 46, 48, 50, 52, 54, 56, 58]) },

  // ── High Priest (6) ──
  { class_id: C.high_priest, name: 'Assumptio', slug: 'assumptio', type: 'buff' as const, max_level: 5, target: 'ally' as const, description: 'Reduz dano recebido pelo alvo.', prerequisites: [], icon_url: 'https://browiki.org/images/e/e1/Assumptio.png', position: { x: 0, y: 0 }, levels: lv(5, [20, 20, 20, 20, 20]) },
  { class_id: C.high_priest, name: 'Basilica', slug: 'basilica', type: 'support' as const, max_level: 5, target: 'area' as const, description: 'Área invulnerável sagrada.', prerequisites: [], icon_url: dp(362), position: { x: 1, y: 0 }, levels: lv(5, [80, 80, 80, 80, 80]) },
  { class_id: C.high_priest, name: 'Kyrie Eleison', slug: 'kyrie-eleison', type: 'buff' as const, max_level: 10, target: 'ally' as const, description: 'Barreira que absorve dano físico.', prerequisites: [], icon_url: 'https://browiki.org/images/f/f4/Kyrie_Eleison.png', position: { x: 2, y: 0 }, levels: lv(10, [20, 20, 20, 20, 20, 20, 20, 20, 20, 20]) },
  { class_id: C.high_priest, name: 'Clementia', slug: 'clementia', type: 'buff' as const, max_level: 5, target: 'area' as const, description: 'Blessing em área.', prerequisites: [], icon_url: 'https://browiki.org/images/6/6d/Clementia.png', position: { x: 3, y: 0 }, levels: lv(5, [200, 220, 240, 260, 280]) },
  { class_id: C.high_priest, name: 'Canto Candidus', slug: 'canto-candidus', type: 'buff' as const, max_level: 5, target: 'area' as const, description: 'Increase AGI em área.', prerequisites: [], icon_url: 'https://browiki.org/images/7/7e/Canto_Candidus.png', position: { x: 4, y: 0 }, levels: lv(5, [200, 220, 240, 260, 280]) },
  { class_id: C.high_priest, name: 'Mace Mastery', slug: 'mace-mastery', type: 'passive' as const, max_level: 10, description: 'Aumenta ATK com maças.', prerequisites: [], icon_url: dp(365), position: { x: 0, y: 2 }, levels: lv(10, [0]) },

  // ── Archbishop (6) ──
  { class_id: C.archbishop, name: 'Renovatio', slug: 'renovatio', type: 'support' as const, max_level: 1, target: 'ally' as const, description: 'Cura contínua no alvo.', prerequisites: [], icon_url: 'https://browiki.org/images/1/1d/Renovatio.png', position: { x: 0, y: 0 }, levels: lv(1, [40]) },
  { class_id: C.archbishop, name: 'Highness Heal', slug: 'highness-heal', type: 'active' as const, max_level: 5, target: 'ally' as const, description: 'Heal poderoso.', prerequisites: [], icon_url: dp(2049), position: { x: 1, y: 0 }, levels: lv(5, [70, 100, 130, 160, 190]) },
  { class_id: C.archbishop, name: 'Expiatio', slug: 'expiatio', type: 'buff' as const, max_level: 5, target: 'ally' as const, description: 'Arma do alvo ignora defesa.', prerequisites: [], icon_url: 'https://browiki.org/images/5/55/Expiatio.png', position: { x: 2, y: 0 }, levels: lv(5, [35, 40, 45, 50, 55]) },
  { class_id: C.archbishop, name: 'Praefatio', slug: 'praefatio', type: 'buff' as const, max_level: 10, target: 'area' as const, description: 'Kyrie Eleison em área.', prerequisites: [], icon_url: 'https://browiki.org/images/6/6a/Praefatio.png', position: { x: 3, y: 0 }, levels: lv(10, [60, 64, 68, 72, 76, 80, 84, 88, 92, 96]) },
  { class_id: C.archbishop, name: 'Adoramus', slug: 'adoramus', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Ataque sagrado poderoso que cega.', prerequisites: [], icon_url: 'https://browiki.org/images/4/4f/Adoramus.png', position: { x: 4, y: 0 }, levels: lv(10, [20, 24, 28, 32, 36, 40, 44, 48, 52, 56]) },
  { class_id: C.archbishop, name: 'Sacrament', slug: 'sacrament', type: 'buff' as const, max_level: 5, target: 'ally' as const, description: 'Reduz tempo fixo de conjuração.', prerequisites: [], icon_url: dp(2053), position: { x: 4, y: 2 }, levels: lv(5, [60, 60, 60, 60, 60]) },

  // ── Monk (9) ──
  { _id: S.iron_fists, class_id: C.monk, name: 'Iron Fists', slug: 'iron-fists', type: 'passive' as const, max_level: 10, description: 'Aumenta ATK desarmado.', prerequisites: [], icon_url: dp(259), position: { x: 0, y: 0 }, levels: lv(10, [0]) },
  { _id: S.call_spirits, class_id: C.monk, name: 'Call Spirits', slug: 'call-spirits', type: 'active' as const, max_level: 5, target: 'self' as const, description: 'Invoca esferas espirituais.', prerequisites: [], icon_url: dp(261), position: { x: 1, y: 0 }, levels: lv(5, [8, 8, 8, 8, 8]) },
  { class_id: C.monk, name: 'Throw Spirit Sphere', slug: 'throw-spirit-sphere', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Arremessa esferas no inimigo.', prerequisites: [{ skill_id: S.call_spirits, required_level: 1 }], icon_url: dp(262), position: { x: 1, y: 2 }, levels: lv(5, [10, 10, 10, 10, 10]) },
  { class_id: C.monk, name: 'Occult Impaction', slug: 'occult-impaction', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Dano baseado na DEF do inimigo.', prerequisites: [], icon_url: dp(263), position: { x: 2, y: 0 }, levels: lv(5, [13, 14, 15, 16, 17]) },
  { _id: S.chain_combo, class_id: C.monk, name: 'Chain Combo', slug: 'chain-combo', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Combo após ataque normal.', prerequisites: [], icon_url: dp(264), position: { x: 3, y: 0 }, levels: lv(5, [11, 11, 11, 11, 11]) },
  { _id: S.combo_finish, class_id: C.monk, name: 'Combo Finish', slug: 'combo-finish', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Finaliza combo com golpe poderoso.', prerequisites: [{ skill_id: S.chain_combo, required_level: 3 }], icon_url: dp(265), position: { x: 3, y: 2 }, levels: lv(5, [11, 11, 11, 11, 11]) },
  { class_id: C.monk, name: 'Guillotine Fist', slug: 'guillotine-fist', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Golpe devastador que consome todas as esferas.', prerequisites: [{ skill_id: S.combo_finish, required_level: 3 }], icon_url: dp(266), position: { x: 4, y: 2 }, levels: lv(5, [1, 1, 1, 1, 1]) },
  { class_id: C.monk, name: 'Body Relocation', slug: 'body-relocation', type: 'active' as const, max_level: 2, target: 'self' as const, description: 'Teleporte instantâneo.', prerequisites: [], icon_url: dp(267), position: { x: 4, y: 0 }, levels: lv(2, [14, 14]) },
  { class_id: C.monk, name: 'Dodge', slug: 'dodge', type: 'passive' as const, max_level: 10, description: 'Chance de esquivar ataques.', prerequisites: [], icon_url: dp(260), position: { x: 0, y: 2 }, levels: lv(10, [0]) },

  // ── Champion (6) ──
  { class_id: C.champion, name: 'Tiger Cannon', slug: 'tiger-cannon', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Golpe de tigre devastador.', prerequisites: [], icon_url: dp(407), position: { x: 0, y: 0 }, levels: lv(10, [20, 24, 28, 32, 36, 40, 44, 48, 52, 56]) },
  { class_id: C.champion, name: 'Gates of Hell', slug: 'gates-of-hell', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Ataque de custo massivo com dano supremo.', prerequisites: [], icon_url: dp(408), position: { x: 1, y: 0 }, levels: lv(10, [100, 110, 120, 130, 140, 150, 160, 170, 180, 190]) },
  { class_id: C.champion, name: 'Raging Palm Strike', slug: 'raging-palm-strike', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Palma flamejante.', prerequisites: [], icon_url: dp(409), position: { x: 2, y: 0 }, levels: lv(5, [4, 4, 4, 4, 4]) },
  { class_id: C.champion, name: 'Glacier Fist', slug: 'glacier-fist', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Punho de gelo paralisante.', prerequisites: [], icon_url: dp(410), position: { x: 3, y: 0 }, levels: lv(5, [4, 4, 4, 4, 4]) },
  { class_id: C.champion, name: 'Fallen Empire', slug: 'fallen-empire', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Golpe que derruba o inimigo.', prerequisites: [], icon_url: dp(411), position: { x: 4, y: 0 }, levels: lv(5, [4, 4, 4, 4, 4]) },
  { class_id: C.champion, name: 'Critical Explosion', slug: 'critical-explosion', type: 'buff' as const, max_level: 5, target: 'self' as const, description: 'Aumenta dano crítico massivamente.', prerequisites: [], icon_url: dp(412), position: { x: 0, y: 2 }, levels: lv(5, [20, 20, 20, 20, 20]) },

  // ── Sura (6) ──
  { class_id: C.sura, name: 'Tiger Cannon Enhanced', slug: 'tiger-cannon-enhanced', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Tiger Cannon versão Sura.', prerequisites: [], icon_url: dp(2301), position: { x: 0, y: 0 }, levels: lv(10, [24, 28, 32, 36, 40, 44, 48, 52, 56, 60]) },
  { class_id: C.sura, name: 'Knuckle Boost', slug: 'knuckle-boost', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Projétil de punho à distância.', prerequisites: [], icon_url: dp(2302), position: { x: 1, y: 0 }, levels: lv(10, [20, 22, 24, 26, 28, 30, 32, 34, 36, 38]) },
  { class_id: C.sura, name: 'Howling of Lion', slug: 'howling-of-lion', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Rugido que atordoa inimigos.', prerequisites: [], icon_url: dp(2303), position: { x: 2, y: 0 }, levels: lv(5, [40, 44, 48, 52, 56]) },
  { class_id: C.sura, name: 'Earth Shaker', slug: 'earth-shaker', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Tremor que revela e dano em escondidos.', prerequisites: [], icon_url: dp(2304), position: { x: 3, y: 0 }, levels: lv(5, [50, 56, 62, 68, 74]) },
  { class_id: C.sura, name: 'Lightning Walk', slug: 'lightning-walk', type: 'buff' as const, max_level: 5, target: 'self' as const, description: 'Move instantaneamente ao ser alvo de magia.', prerequisites: [], icon_url: dp(2305), position: { x: 4, y: 0 }, levels: lv(5, [40, 40, 40, 40, 40]) },
  { class_id: C.sura, name: 'Dragon Combo', slug: 'dragon-combo', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Combo do dragão em sequência.', prerequisites: [], icon_url: dp(2306), position: { x: 0, y: 2 }, levels: lv(10, [4, 4, 4, 4, 4, 4, 4, 4, 4, 4]) },
]
