import { C, S, lv } from './shared'

export const merchantChainSkills = [
  // ── Merchant (8) ──
  { _id: S.discount, class_id: C.merchant, name: 'Desconto', slug: 'discount', type: 'passive' as const, max_level: 10, description: 'Reduz preço de compra em NPC.', prerequisites: [], icon_url: 'https://browiki.org/images/3/35/Desconto.png', position: { x: 0, y: 0 }, levels: lv(10, [0]) },
  { _id: S.overcharge, class_id: C.merchant, name: 'Superfaturar', slug: 'overcharge', type: 'passive' as const, max_level: 10, description: 'Aumenta preço de venda em NPC.', prerequisites: [], icon_url: 'https://browiki.org/images/2/21/Superfaturar.png', position: { x: 1, y: 0 }, levels: lv(10, [0]) },
  { class_id: C.merchant, name: 'Aumentar Capacidade de Carga', slug: 'enlarge-weight-limit', type: 'passive' as const, max_level: 10, description: 'Aumenta capacidade de peso.', prerequisites: [], icon_url: 'https://browiki.org/images/0/09/Aumentar_Capacidade_de_Carga.png', position: { x: 2, y: 0 }, levels: lv(10, [0]) },
  { _id: S.pushcart, class_id: C.merchant, name: 'Usar Carrinho', slug: 'pushcart', type: 'passive' as const, max_level: 5, description: 'Permite usar carrinho.', prerequisites: [], icon_url: 'https://browiki.org/images/4/47/Usar_Carrinho.png', position: { x: 3, y: 0 }, levels: lv(5, [0]) },
  { _id: S.vending, class_id: C.merchant, name: 'Comércio', slug: 'vending', type: 'active' as const, max_level: 4, target: 'self' as const, description: 'Abre uma loja para vender itens.', prerequisites: [{ skill_id: S.pushcart, required_level: 2 }], icon_url: 'https://browiki.org/images/5/5a/Com%C3%A9rcio.png', position: { x: 3, y: 2 }, levels: lv(4, [30, 30, 30, 30]) },
  { class_id: C.merchant, name: 'Mammonita', slug: 'mammonite', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Ataque poderoso que custa zeny.', prerequisites: [], icon_url: 'https://browiki.org/images/7/7b/Mammonita.png', position: { x: 4, y: 0 }, levels: lv(10, [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]) },
  { class_id: C.merchant, name: 'Personalizar Carrinho', slug: 'change-cart', type: 'active' as const, max_level: 4, target: 'self' as const, description: 'Muda aparência do carrinho.', prerequisites: [], icon_url: 'https://browiki.org/images/8/82/Personalizar_Carrinho.png', position: { x: 4, y: 2 }, levels: lv(4, [0, 0, 0, 0]) },
  { class_id: C.merchant, name: 'Identificar Item', slug: 'item-appraisal', type: 'active' as const, max_level: 1, target: 'self' as const, description: 'Identifica itens desconhecidos.', prerequisites: [], icon_url: 'https://browiki.org/images/1/18/Identificar_Item.png', position: { x: 1, y: 2 }, levels: lv(1, [10]) },

  // ── Blacksmith (8) ──
  { class_id: C.blacksmith, name: 'Adrenalina Pura', slug: 'adrenaline-rush', type: 'buff' as const, max_level: 5, target: 'area' as const, description: 'Aumenta ASPD com armas de impacto.', prerequisites: [], icon_url: 'https://browiki.org/images/5/52/Adrenalina_Pura.png', position: { x: 0, y: 0 }, levels: lv(5, [20, 20, 20, 20, 20]) },
  { class_id: C.blacksmith, name: 'Manejo Perfeito', slug: 'weapon-perfection', type: 'buff' as const, max_level: 5, target: 'self' as const, description: 'Remove penalidade de tamanho.', prerequisites: [], icon_url: 'https://browiki.org/images/b/bd/Manejo_Perfeito.png', position: { x: 1, y: 0 }, levels: lv(5, [18, 18, 18, 18, 18]) },
  { class_id: C.blacksmith, name: 'Amplificar Poder', slug: 'maximize-power', type: 'buff' as const, max_level: 5, target: 'self' as const, description: 'ATK sempre no valor máximo.', prerequisites: [], icon_url: 'https://browiki.org/images/c/c5/Amplificar_Poder.png', position: { x: 2, y: 0 }, levels: lv(5, [10, 10, 10, 10, 10]) },
  { class_id: C.blacksmith, name: 'Força Violenta', slug: 'power-thrust', type: 'buff' as const, max_level: 5, target: 'area' as const, description: 'Aumenta ATK do grupo (pode quebrar arma).', prerequisites: [], icon_url: 'https://browiki.org/images/3/30/For%C3%A7a_Violenta.png', position: { x: 3, y: 0 }, levels: lv(5, [12, 12, 12, 12, 12]) },
  { class_id: C.blacksmith, name: 'Martelo de Thor', slug: 'hammerfall', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Atordoa inimigos em área.', prerequisites: [], icon_url: 'https://browiki.org/images/0/06/Martelo_de_Thor.png', position: { x: 4, y: 0 }, levels: lv(5, [10, 10, 10, 10, 10]) },
  { class_id: C.blacksmith, name: 'Trabalhar Ferro', slug: 'skin-tempering', type: 'passive' as const, max_level: 5, description: 'Resistência a fogo e neutro.', prerequisites: [], icon_url: 'https://browiki.org/images/1/12/Trabalhar_Ferro.png', position: { x: 0, y: 2 }, levels: lv(5, [0]) },
  { class_id: C.blacksmith, name: 'Punho Firme', slug: 'hilt-binding', type: 'passive' as const, max_level: 1, description: 'Aumenta ATK.', prerequisites: [], icon_url: 'https://browiki.org/images/b/b8/Punho_Firme.png', position: { x: 1, y: 2 }, levels: lv(1, [0]) },
  { class_id: C.blacksmith, name: 'Perícia em Armamento', slug: 'enchantedstone-craft', type: 'active' as const, max_level: 5, target: 'self' as const, description: 'Cria pedras elementais.', prerequisites: [], icon_url: 'https://browiki.org/images/d/d1/Per%C3%ADcia_em_Armamento.png', position: { x: 4, y: 2 }, levels: lv(5, [30, 30, 30, 30, 30]) },

  // ── Alchemist (8) ──
  { class_id: C.alchemist, name: 'Preparar Poção', slug: 'pharmacy', type: 'active' as const, max_level: 10, target: 'self' as const, description: 'Cria poções e itens alquímicos.', prerequisites: [], icon_url: 'https://browiki.org/images/7/7d/Preparar_Po%C3%A7%C3%A3o.png', position: { x: 0, y: 0 }, levels: lv(10, [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]) },
  { class_id: C.alchemist, name: 'Arremessar Poção', slug: 'potion-pitcher', type: 'active' as const, max_level: 5, target: 'ally' as const, description: 'Arremessa poção para curar aliado.', prerequisites: [], icon_url: 'https://browiki.org/images/9/9a/Arremessar_Po%C3%A7%C3%A3o.png', position: { x: 1, y: 0 }, levels: lv(5, [1, 1, 1, 1, 1]) },
  { class_id: C.alchemist, name: 'Fogo Grego', slug: 'aid-potion', type: 'active' as const, max_level: 5, target: 'ally' as const, description: 'Usa poção em aliado à distância.', prerequisites: [], icon_url: 'https://browiki.org/images/4/42/Fogo_Grego.png', position: { x: 2, y: 0 }, levels: lv(5, [10, 10, 10, 10, 10]) },
  { class_id: C.alchemist, name: 'Despertar Homunculus', slug: 'bioethics', type: 'passive' as const, max_level: 1, description: 'Permite criar homúnculos.', prerequisites: [], icon_url: 'https://browiki.org/images/a/a6/Despertar_Homunculus.png', position: { x: 3, y: 0 }, levels: lv(1, [0]) },
  { class_id: C.alchemist, name: 'Terror Ácido', slug: 'acid-terror', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Ataque ácido que pode quebrar armadura.', prerequisites: [], icon_url: 'https://browiki.org/images/6/60/Terror_%C3%81cido.png', position: { x: 4, y: 0 }, levels: lv(10, [15, 15, 15, 15, 15, 15, 15, 15, 15, 15]) },
  { class_id: C.alchemist, name: 'Vaporizar', slug: 'bomb', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Arremessa bomba de garrafa.', prerequisites: [], icon_url: 'https://browiki.org/images/a/a6/Vaporizar.png', position: { x: 4, y: 2 }, levels: lv(5, [10, 10, 10, 10, 10]) },
  { class_id: C.alchemist, name: 'Criar Monstro Planta', slug: 'demonstration', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Cria fogo no chão que queima.', prerequisites: [], icon_url: 'https://browiki.org/images/2/26/Criar_Monstro_Planta.png', position: { x: 3, y: 2 }, levels: lv(5, [10, 10, 10, 10, 10]) },
  { class_id: C.alchemist, name: 'Criar Esfera Marinha', slug: 'berserk-pitcher', type: 'active' as const, max_level: 5, target: 'ally' as const, description: 'Arremessa garrafa de berserk potion.', prerequisites: [], icon_url: 'https://browiki.org/images/e/e3/Criar_Esfera_Marinha.png', position: { x: 0, y: 2 }, levels: lv(5, [10, 10, 10, 10, 10]) },

  // ── Whitesmith (5) ──
  { class_id: C.whitesmith, name: 'Impulso no Carrinho', slug: 'cart-boost', type: 'buff' as const, max_level: 5, target: 'self' as const, description: 'Aumenta velocidade com carrinho.', prerequisites: [], icon_url: 'https://browiki.org/images/5/52/Impulso_no_Carrinho.png', position: { x: 0, y: 0 }, levels: lv(5, [12, 12, 12, 12, 12]) },
  { class_id: C.whitesmith, name: 'Adrenalina Concentrada', slug: 'full-adrenaline-rush', type: 'buff' as const, max_level: 5, target: 'area' as const, description: 'Adrenaline Rush para todas as armas.', prerequisites: [], icon_url: 'https://browiki.org/images/8/88/Adrenalina_Concentrada.png', position: { x: 1, y: 0 }, levels: lv(5, [36, 36, 36, 36, 36]) },
  { class_id: C.whitesmith, name: 'Golpe Estilhaçante', slug: 'meltdown', type: 'active' as const, max_level: 10, target: 'self' as const, description: 'Chance de quebrar equipamento do alvo.', prerequisites: [], icon_url: 'https://browiki.org/images/6/63/Golpe_Estilha%C3%A7ante.png', position: { x: 2, y: 0 }, levels: lv(10, [50, 50, 50, 50, 50, 50, 50, 50, 50, 50]) },
  { class_id: C.whitesmith, name: 'Força Violentíssima', slug: 'maximum-over-thrust', type: 'buff' as const, max_level: 5, target: 'self' as const, description: 'Aumenta ATK massivamente.', prerequisites: [], icon_url: 'https://browiki.org/images/f/f1/For%C3%A7a_Violent%C3%ADssima.png', position: { x: 3, y: 0 }, levels: lv(5, [15, 15, 15, 15, 15]) },
  { class_id: C.whitesmith, name: 'Consertar Armas', slug: 'weapon-repair', type: 'active' as const, max_level: 5, target: 'ally' as const, description: 'Repara equipamento quebrado.', prerequisites: [], icon_url: 'https://browiki.org/images/2/22/Consertar_Armas.png', position: { x: 4, y: 0 }, levels: lv(5, [30, 30, 30, 30, 30]) },

  // ── Mechanic (6) ──
  { class_id: C.mechanic, name: 'Fúria do Furacão', slug: 'power-swing', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Golpe pesado com mecha.', prerequisites: [], icon_url: 'https://browiki.org/images/7/75/F%C3%BAria_do_Furac%C3%A3o.png', position: { x: 0, y: 0 }, levels: lv(5, [18, 22, 26, 30, 34]) },
  { class_id: C.mechanic, name: 'Canhão', slug: 'arm-cannon', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Dispara canhão do braço mecha.', prerequisites: [], icon_url: 'https://browiki.org/images/8/82/Canh%C3%A3o.png', position: { x: 1, y: 0 }, levels: lv(5, [30, 36, 42, 48, 54]) },
  { class_id: C.mechanic, name: 'Gás Criogênico', slug: 'ice-launcher', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Lança gelo que congela inimigos.', prerequisites: [], icon_url: 'https://browiki.org/images/b/bc/G%C3%A1s_Criog%C3%AAnico.png', position: { x: 2, y: 0 }, levels: lv(5, [30, 34, 38, 42, 46]) },
  { class_id: C.mechanic, name: 'Metralhadora', slug: 'vulcan-arm', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Rajada de tiros do braço.', prerequisites: [], icon_url: 'https://browiki.org/images/7/74/Metralhadora.png', position: { x: 3, y: 0 }, levels: lv(5, [2, 2, 2, 2, 2]) },
  { class_id: C.mechanic, name: 'Bate Estaca', slug: 'pile-bunker', type: 'active' as const, max_level: 5, target: 'enemy' as const, description: 'Golpe devastador com pilão.', prerequisites: [], icon_url: 'https://browiki.org/images/c/c5/Bate_Estaca.png', position: { x: 4, y: 0 }, levels: lv(5, [50, 50, 50, 50, 50]) },
  { class_id: C.mechanic, name: 'Sabedoria de Hefesto', slug: 'madogear-license', type: 'passive' as const, max_level: 5, description: 'Permite pilotar Madogear.', prerequisites: [], icon_url: 'https://browiki.org/images/3/34/Sabedoria_de_Hefesto.png', position: { x: 0, y: 2 }, levels: lv(5, [0]) },

  // ── Creator (6) ──
  { class_id: C.creator, name: 'Bomba Ácida', slug: 'acid-demonstration', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Combina ácido + bomba para dano baseado em VIT.', prerequisites: [], icon_url: 'https://browiki.org/images/9/90/Bomba_%C3%81cida.png', position: { x: 0, y: 0 }, levels: lv(10, [30, 30, 30, 30, 30, 30, 30, 30, 30, 30]) },
  { class_id: C.creator, name: 'Despertar Homunculus', slug: 'call-homunculus', type: 'active' as const, max_level: 1, target: 'self' as const, description: 'Invoca o homúnculo.', prerequisites: [], icon_url: 'https://browiki.org/images/a/a6/Despertar_Homunculus.png', position: { x: 1, y: 0 }, levels: lv(1, [10]) },
  { class_id: C.creator, name: 'Ressuscitar Homunculus', slug: 'homunculus-resurrection', type: 'active' as const, max_level: 5, target: 'self' as const, description: 'Revive o homúnculo.', prerequisites: [], icon_url: 'https://browiki.org/images/8/83/Ressuscitar_Homunculus.png', position: { x: 2, y: 0 }, levels: lv(5, [10, 10, 10, 10, 10]) },
  { class_id: C.creator, name: 'Pesquisa de Poções', slug: 'bio-explosion', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Explosão biológica em área.', prerequisites: [], icon_url: 'https://browiki.org/images/4/49/Pesquisa_de_Po%C3%A7%C3%B5es.png', position: { x: 3, y: 0 }, levels: lv(5, [20, 24, 28, 32, 36]) },
  { class_id: C.creator, name: 'Criar Esfera Marinha', slug: 'marine-sphere', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Invoca esferas marinhas que explodem.', prerequisites: [], icon_url: 'https://browiki.org/images/e/e3/Criar_Esfera_Marinha.png', position: { x: 4, y: 0 }, levels: lv(5, [10, 10, 10, 10, 10]) },
  { class_id: C.creator, name: 'Criação Espiritual de Poções I', slug: 'twilight-pharmacy', type: 'active' as const, max_level: 3, target: 'self' as const, description: 'Produção em massa de poções.', prerequisites: [], icon_url: 'https://browiki.org/images/0/00/Cria%C3%A7%C3%A3o_Espiritual_de_Po%C3%A7%C3%B5es.png', position: { x: 4, y: 2 }, levels: lv(3, [200, 200, 200]) },

  // ── Genetic (6) ──
  { class_id: C.genetic, name: 'Canhão de Prótons', slug: 'fire-expansion', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Expande fogo com efeitos variados.', prerequisites: [], icon_url: 'https://browiki.org/images/6/6d/Canh%C3%A3o_de_Pr%C3%B3tons.png', position: { x: 0, y: 0 }, levels: lv(5, [30, 36, 42, 48, 54]) },
  { class_id: C.genetic, name: 'Reação Alquímica', slug: 'acid-bomb', type: 'active' as const, max_level: 10, target: 'enemy' as const, description: 'Versão melhorada de Acid Demonstration.', prerequisites: [], icon_url: 'https://browiki.org/images/5/5c/Rea%C3%A7%C3%A3o_Alqu%C3%ADmica.png', position: { x: 1, y: 0 }, levels: lv(10, [30, 30, 30, 30, 30, 30, 30, 30, 30, 30]) },
  { class_id: C.genetic, name: 'Planta Infernal', slug: 'hells-plant', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Planta carnívora que ataca inimigos.', prerequisites: [], icon_url: 'https://browiki.org/images/2/2c/Planta_Infernal.png', position: { x: 2, y: 0 }, levels: lv(5, [20, 24, 28, 32, 36]) },
  { class_id: C.genetic, name: 'Muralha de Espinhos', slug: 'crazy-weed', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Ervas daninhas que removem traps e dano.', prerequisites: [], icon_url: 'https://browiki.org/images/4/4c/Muralha_de_Espinhos.png', position: { x: 3, y: 0 }, levels: lv(5, [18, 22, 26, 30, 34]) },
  { class_id: C.genetic, name: 'Grito da Mandrágora', slug: 'howling-of-mandragora', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Grito que drena SP e causa status.', prerequisites: [], icon_url: 'https://browiki.org/images/4/4a/Grito_da_Mandr%C3%A1gora.png', position: { x: 4, y: 0 }, levels: lv(5, [40, 44, 48, 52, 56]) },
  { class_id: C.genetic, name: 'Armadilha de Espinhos', slug: 'spore-explosion', type: 'active' as const, max_level: 5, target: 'area' as const, description: 'Esporos que explodem em cadeia.', prerequisites: [], icon_url: 'https://browiki.org/images/a/a9/Armadilha_de_Espinhos.png', position: { x: 4, y: 2 }, levels: lv(5, [24, 28, 32, 36, 40]) },
]
